import { Conversation, Message, Interactie, Klant, Opdracht, Taak, ContactPersoon } from '@/types';

// ============================================
// MOCK CONVERSATIONS
// ============================================
export const mockConversations: Conversation[] = [
  {
    id: '1',
    conversation_nummer: 'CONV-2024-0001',
    status: 'open',
    klant_id: '1',
    klant_naam: 'Hans Mulder (particulier)',
    contactpersoon_id: '1',
    primary_channel: 'WhatsApp',
    all_channels: ['WhatsApp', 'E-mail'],
    onderwerp: 'Vraag over auto van de zaak',
    tags: ['Financieel', 'Auto van de zaak'],
    created_at: '2025-10-20T09:15:00Z',
    updated_at: '2025-10-20T09:27:00Z',
    last_message_at: '2025-10-20T09:27:00Z',
    toegewezen_aan: 'Harm-Jan Kaspers',
    team_members: ['Harm-Jan Kaspers'],
    opvolging_nodig: true,
    opvolging_datum: '2025-10-25',
    priority: 'normal',
    is_unread: false,
    message_count: 1,
    sentiment: 'positive',
  },
  {
    id: '2',
    conversation_nummer: 'CONV-2024-0002',
    status: 'open',
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    primary_channel: 'Zoom',
    all_channels: ['Zoom', 'WhatsApp'],
    onderwerp: 'Intake procesoptimalisatie',
    tags: ['Intake', 'Procesoptimalisatie', 'Groei'],
    created_at: '2025-10-18T14:30:00Z',
    updated_at: '2025-10-18T15:15:00Z',
    last_message_at: '2025-10-18T15:15:00Z',
    toegewezen_aan: 'Jan Jansen',
    team_members: ['Jan Jansen'],
    opvolging_nodig: true,
    opvolging_datum: '2025-10-22',
    priority: 'high',
    is_unread: false,
    message_count: 1,
    sentiment: 'positive',
  },
];

// ============================================
// MOCK MESSAGES
// ============================================
export const mockMessages: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      conversation_id: '1',
      content: 'Hello, I received a damaged product in my order #12345',
      timestamp: '2024-10-23T14:32:00Z',
      channel: 'WhatsApp',
      direction: 'inbound',
      from: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
        channel_identifier: '+31612345678',
      },
      to: {
        id: 'team1',
        naam: 'Kaspers Advies',
        type: 'team_member',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_123',
        status: 'delivered',
      },
      is_thread_start: true,
      delivery_status: 'delivered',
      attachments: [],
      contains_question: true,
      action_required: true,
      marked_important: false,
    },
    {
      id: 'm2',
      conversation_id: '1',
      content: "I'm very sorry to hear that. Can you send me a photo of the damage?",
      timestamp: '2024-10-23T14:33:00Z',
      channel: 'WhatsApp',
      direction: 'outbound',
      from: {
        id: 'team1',
        naam: 'Harm-Jan Kaspers',
        type: 'team_member',
      },
      to: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_124',
        status: 'read',
      },
      is_thread_start: false,
      delivery_status: 'read',
      read_at: '2024-10-23T14:33:30Z',
      attachments: [],
      contains_question: true,
      action_required: false,
      marked_important: false,
    },
    {
      id: 'm3',
      conversation_id: '1',
      content: 'Sure, here it is',
      timestamp: '2024-10-23T14:35:00Z',
      channel: 'WhatsApp',
      direction: 'inbound',
      from: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      to: {
        id: 'team1',
        naam: 'Kaspers Advies',
        type: 'team_member',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_125',
        status: 'delivered',
        media_type: 'image',
      },
      is_thread_start: false,
      delivery_status: 'delivered',
      attachments: [
        {
          id: 'att1',
          filename: 'damaged_product.jpg',
          file_type: 'image/jpeg',
          file_size: 245680,
          url: '/placeholder.svg',
          uploaded_at: '2024-10-23T14:35:00Z',
          uploaded_by: 'Rosemary Braun',
        },
      ],
      contains_question: false,
      action_required: true,
      marked_important: false,
    },
    {
      id: 'm4',
      conversation_id: '1',
      content: "Thank you. We'll send you a replacement immediately.",
      timestamp: '2024-10-23T14:36:00Z',
      channel: 'WhatsApp',
      direction: 'outbound',
      from: {
        id: 'team1',
        naam: 'Harm-Jan Kaspers',
        type: 'team_member',
      },
      to: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_126',
        status: 'read',
      },
      is_thread_start: false,
      delivery_status: 'read',
      read_at: '2024-10-23T14:36:15Z',
      attachments: [],
      contains_question: false,
      action_required: false,
      marked_important: false,
    },
  ],
};

// ============================================
// MOCK KLANTEN (10 realistic clients from CSV)
// ============================================
export const mockKlanten: Klant[] = [
  // Hans Mulder - Particulier (privé klant van bedrijfseigenaar)
  {
    id: '1',
    klant_nummer: 'K-2021-045',
    naam: 'Hans Mulder (particulier)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'h.mulder@gmail.com',
    telefoonnummer: '+31-599-612345',
    adres: 'Stationsstraat 12',
    postcode: '9501 AB',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '234567891',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-03-15',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['2'], // Link to Installatiebedrijf Mulder BV
    relatie_type: 'Eigenaar van',
    notities: 'DGA van Installatiebedrijf Mulder BV. Privé aangifte + optimalisatie salary/dividend.',
    tags: ['DGA', 'Particulier'],
    voorkeur_kanaal: 'Telefoon',
    taal_voorkeur: 'nl',
  },
  // Installatiebedrijf Mulder BV - Zakelijk (bedrijf van Hans Mulder)
  {
    id: '2',
    klant_nummer: 'K-2021-046',
    naam: 'Installatiebedrijf Mulder BV',
    type_klant: 'MKB',
    klant_type_details: 'Zakelijk - BV',
    email: 'info@mulder-installatie.nl',
    telefoonnummer: '+31-599-612388',
    adres: 'Industrieweg 8',
    postcode: '9501 DK',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    kvk_nummer: '45678123',
    btw_nummer: 'NL456781234B01',
    website: 'www.mulder-installatie.nl',
    branche: 'Installatiebedrijf',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-03-15',
    jaren_actief_als_ondernemer: 4,
    facturatie_frequentie: 'Maandelijks',
    groei_fase: 'Groei',
    gerelateerde_klanten: ['1'], // Link to Hans Mulder particulier
    relatie_type: 'Eigendom van',
    notities: 'CV-installaties, sanitair, duurzame energie. 3 medewerkers, groeiambitie naar 8 medewerkers.',
    tags: ['MKB', 'Installatie', 'Groei'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Lisa de Vries - Particulier (privé klant van onderneemster)
  {
    id: '3',
    klant_nummer: 'K-2020-088',
    naam: 'Lisa de Vries (privé)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'lisa.devries@hotmail.com',
    telefoonnummer: '+31-599-623456',
    adres: 'Hoofdstraat 45',
    postcode: '9501 CC',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '345678902',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Jan Jansen',
    sinds_wanneer_klant: '2020-09-01',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['4'], // Link to Webshop TechGadgets
    relatie_type: 'Eigenaar van',
    notities: 'Eigenaar webshop TechGadgets. Privé aangifte IB.',
    tags: ['Particulier', 'ZZP'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Webshop TechGadgets - Zakelijk (eenmanszaak van Lisa)
  {
    id: '4',
    klant_nummer: 'K-2020-089',
    naam: 'Webshop TechGadgets',
    type_klant: 'ZZP',
    klant_type_details: 'Zakelijk - Eenmanszaak',
    email: 'info@techgadgets.nl',
    telefoonnummer: '+31-599-623457',
    adres: 'Hoofdstraat 45',
    postcode: '9501 CC',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    kvk_nummer: '56789234',
    btw_nummer: 'NL567892345B01',
    website: 'www.techgadgets.nl',
    branche: 'E-commerce',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Jan Jansen',
    sinds_wanneer_klant: '2020-09-01',
    jaren_actief_als_ondernemer: 4,
    facturatie_frequentie: 'Kwartaal',
    groei_fase: 'Schaal-op',
    gerelateerde_klanten: ['3'], // Link to Lisa de Vries privé
    relatie_type: 'Eigendom van',
    notities: 'Online verkoop gadgets en elektronica. Groei 40% per jaar, overweegt personeel.',
    tags: ['ZZP', 'E-commerce', 'Groei'],
    voorkeur_kanaal: 'WhatsApp',
    taal_voorkeur: 'nl',
  },
  // P. Bakker & M. Bakker-Smit - Particulier (gehuwd koppel)
  {
    id: '5',
    klant_nummer: 'K-2022-101',
    naam: 'P. Bakker & M. Bakker-Smit',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - gehuwd',
    email: 'p.bakker@gmail.com',
    telefoonnummer: '+31-599-634567',
    adres: 'Europaweg 23',
    postcode: '9501 TG',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '456789013',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Linda Prins',
    sinds_wanneer_klant: '2022-01-10',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: [],
    notities: 'Gezamenlijke IB-aangifte. Toeslagen (2 kinderen). Peter werkt in loondienst bij Siemens.',
    tags: ['Particulier', 'Gezin', 'Toeslagen'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Fysiotherapie Vitaal VOF - Zakelijk (vennootschap)
  {
    id: '6',
    klant_nummer: 'K-2021-120',
    naam: 'Fysiotherapie Vitaal VOF',
    type_klant: 'MKB',
    klant_type_details: 'Zakelijk - VOF/Maatschap',
    email: 'info@fysiovitaal.nl',
    telefoonnummer: '+31-599-645678',
    adres: 'Wilhelminastraat 12',
    postcode: '9501 HD',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    kvk_nummer: '67890345',
    btw_nummer: 'NL678903456B01',
    website: 'www.fysiovitaal.nl',
    branche: 'Gezondheidszorg',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-06-01',
    jaren_actief_als_ondernemer: 3,
    facturatie_frequentie: 'Kwartaal',
    groei_fase: 'Professionalisering',
    gerelateerde_klanten: ['7', '8'], // Links to Anne Bakker and Tom Willems
    relatie_type: 'Vennoot',
    notities: 'Fysiotherapiepraktijk, 2 vennoten, 1 medewerker. Overweging omzetting naar BV.',
    tags: ['MKB', 'Gezondheidszorg', 'VOF'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Anne Bakker - Particulier (vennoot VOF)
  {
    id: '7',
    klant_nummer: 'K-2021-121',
    naam: 'Anne Bakker (privé)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'anne.bakker@fysiovitaal.nl',
    telefoonnummer: '+31-599-656789',
    adres: 'Molenstraat 8',
    postcode: '9501 JK',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '567890124',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-06-01',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['6'], // Link to Fysiotherapie Vitaal VOF
    relatie_type: 'Vennoot',
    notities: 'Vennoot Fysiotherapie Vitaal VOF (50%). Privé aangifte winst uit onderneming.',
    tags: ['Particulier', 'Vennoot'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Tom Willems - Particulier (vennoot VOF)
  {
    id: '8',
    klant_nummer: 'K-2021-122',
    naam: 'Tom Willems (privé)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'tom.willems@fysiovitaal.nl',
    telefoonnummer: '+31-599-667890',
    adres: 'Oosterstraat 34',
    postcode: '9501 LP',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '678901235',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-06-01',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['6'], // Link to Fysiotherapie Vitaal VOF
    relatie_type: 'Vennoot',
    notities: 'Vennoot Fysiotherapie Vitaal VOF (50%). Privé aangifte winst uit onderneming.',
    tags: ['Particulier', 'Vennoot'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Slagerij Van Dijk - Zakelijk (eenmanszaak)
  {
    id: '9',
    klant_nummer: 'K-2019-033',
    naam: 'Slagerij Van Dijk',
    type_klant: 'MKB',
    klant_type_details: 'Zakelijk - Eenmanszaak',
    email: 'info@slagerijvandijk.nl',
    telefoonnummer: '+31-599-678901',
    adres: 'Marktplein 5',
    postcode: '9501 AB',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    kvk_nummer: '78901456',
    btw_nummer: 'NL789014567B01',
    website: 'www.slagerijvandijk.nl',
    branche: 'Detailhandel voeding',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Linda Prins',
    sinds_wanneer_klant: '2019-02-01',
    jaren_actief_als_ondernemer: 5,
    facturatie_frequentie: 'Maandelijks',
    groei_fase: 'Digitalisering',
    gerelateerde_klanten: ['10'], // Link to Jan van Dijk privé
    relatie_type: 'Eigendom van',
    notities: 'Traditionele slagerij, bestaat sinds 1995. Nu digitalisering: webshop, online bestellingen.',
    tags: ['MKB', 'Retail', 'Digitalisering'],
    voorkeur_kanaal: 'WhatsApp',
    taal_voorkeur: 'nl',
  },
  // Jan van Dijk - Particulier (eigenaar slagerij)
  {
    id: '10',
    klant_nummer: 'K-2019-034',
    naam: 'Jan van Dijk (privé)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'jan@slagerijvandijk.nl',
    telefoonnummer: '+31-599-678901',
    adres: 'Marktplein 5',
    postcode: '9501 AB',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '789012346',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Linda Prins',
    sinds_wanneer_klant: '2019-02-01',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['9'], // Link to Slagerij Van Dijk
    relatie_type: 'Eigenaar van',
    notities: 'Eigenaar Slagerij Van Dijk. Zoon Pieter werkt mee in bedrijf (geen vennoot).',
    tags: ['Particulier', 'ZZP'],
    voorkeur_kanaal: 'Telefoon',
    taal_voorkeur: 'nl',
  },
];

// ============================================
// MOCK OPDRACHTEN (Realistic opdrachten from CSV)
// ============================================
export const mockOpdrachten: Opdracht[] = [
  {
    id: '1',
    opdracht_nummer: 'OPD-2024-001',
    opdracht_naam: 'IB-aangifte 2024',
    beschrijving: 'Inkomstenbelasting aangifte 2024',
    klant_id: '1',
    klant_naam: 'Hans Mulder (particulier)',
    type_opdracht: 'IB (Inkomstenbelasting)',
    categorie: 'Traditie',
    status: 'Afgerond',
    priority: 'Normaal',
    boekjaar_periode: '2024',
    start_datum: '2025-03-01',
    deadline: '2025-05-01',
    afgerond_datum: '2025-04-15',
    geschat_aantal_uren: 3,
    gefactureerd_bedrag: 450,
    betaald: true,
    betalings_datum: '2025-04-20',
    verantwoordelijk: 'Harm-Jan Kaspers',
    document_ids: [],
    bijzonderheden: 'Hypotheekrenteaftrek eigen woning. DGA-optimalisatie meegenomen.',
  },
  {
    id: '2',
    opdracht_nummer: 'OPD-2024-002',
    opdracht_naam: 'Jaarrekening 2024',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    bedrijfsnaam: 'Installatiebedrijf Mulder BV',
    type_opdracht: 'Jaarrekening',
    categorie: 'Traditie',
    status: 'In behandeling',
    priority: 'Hoog',
    boekjaar_periode: '2024',
    start_datum: '2025-02-01',
    deadline: '2025-05-31',
    geschat_aantal_uren: 12,
    gefactureerd_bedrag: 2400,
    betaald: false,
    verantwoordelijk: 'Harm-Jan Kaspers',
    document_ids: [],
    bijzonderheden: 'Groei 35% t.o.v. 2023. Investering bedrijfswagen Q4.',
  },
  {
    id: '3',
    opdracht_nummer: 'OPD-2024-003',
    opdracht_naam: 'Groeibegeleiding Q2-Q4 2025',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    type_opdracht: 'Groeibegeleiding',
    categorie: 'Groei',
    status: 'In behandeling',
    priority: 'Hoog',
    boekjaar_periode: '2025',
    start_datum: '2025-04-01',
    deadline: '2025-12-31',
    geschat_aantal_uren: 20,
    gefactureerd_bedrag: 3500,
    betaald: false,
    verantwoordelijk: 'Harm-Jan Kaspers',
    document_ids: [],
    beschrijving: 'Begeleiding groei 3 naar 8 medewerkers',
    bijzonderheden: 'Procesoptimalisatie, werving strategie, financiële groeiplan.',
  },
  {
    id: '4',
    opdracht_nummer: 'OPD-2024-004',
    opdracht_naam: 'BTW-aangifte Q1 2025',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    type_opdracht: 'BTW-aangifte',
    categorie: 'Traditie',
    status: 'Afgerond',
    priority: 'Normaal',
    boekjaar_periode: '2025 Q1',
    start_datum: '2025-04-15',
    deadline: '2025-04-30',
    afgerond_datum: '2025-04-28',
    geschat_aantal_uren: 2,
    gefactureerd_bedrag: 350,
    betaald: true,
    betalings_datum: '2025-05-05',
    verantwoordelijk: 'Jan Jansen',
    document_ids: [],
    beschrijving: 'BTW-aangifte eerste kwartaal 2025',
  },
  {
    id: '5',
    opdracht_nummer: 'OPD-2024-005',
    opdracht_naam: 'Jaarrekening 2024',
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    type_opdracht: 'Jaarrekening',
    categorie: 'Traditie',
    status: 'Afgerond',
    priority: 'Normaal',
    boekjaar_periode: '2024',
    start_datum: '2025-02-15',
    deadline: '2025-05-31',
    afgerond_datum: '2025-04-30',
    geschat_aantal_uren: 8,
    gefactureerd_bedrag: 1600,
    betaald: true,
    betalings_datum: '2025-05-10',
    verantwoordelijk: 'Jan Jansen',
    document_ids: [],
    beschrijving: 'Jaarrekening eenmanszaak 2024',
    bijzonderheden: 'Omzetgroei 40%. Voorraadwaardering complex i.v.m. Chinese leveranciers.',
  },
  {
    id: '6',
    opdracht_nummer: 'OPD-2024-006',
    opdracht_naam: 'Procesoptimalisatie webshop',
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    type_opdracht: 'Procesoptimalisatie',
    categorie: 'Groei',
    status: 'In behandeling',
    priority: 'Hoog',
    boekjaar_periode: '2025',
    start_datum: '2025-05-01',
    deadline: '2025-09-30',
    geschat_aantal_uren: 15,
    gefactureerd_bedrag: 2500,
    betaald: false,
    verantwoordelijk: 'Jan Jansen',
    document_ids: [],
    beschrijving: 'Optimalisatie orderverwerking en voorraadmanagement',
    bijzonderheden: 'Doel: 30% tijdsbesparing. Focus op automatisering.',
  },
  {
    id: '7',
    opdracht_nummer: 'OPD-2024-007',
    opdracht_naam: 'IB-aangifte 2024',
    klant_id: '5',
    klant_naam: 'P. Bakker & M. Bakker-Smit',
    type_opdracht: 'IB (Inkomstenbelasting)',
    categorie: 'Traditie',
    status: 'Afgerond',
    priority: 'Normaal',
    boekjaar_periode: '2024',
    start_datum: '2025-03-05',
    deadline: '2025-05-01',
    afgerond_datum: '2025-04-10',
    geschat_aantal_uren: 2,
    gefactureerd_bedrag: 400,
    betaald: true,
    betalings_datum: '2025-04-15',
    verantwoordelijk: 'Linda Prins',
    document_ids: [],
    beschrijving: 'Gezamenlijke IB-aangifte 2024',
    bijzonderheden: 'Peter in loondienst. Hypotheekrenteaftrek.',
  },
  {
    id: '8',
    opdracht_nummer: 'OPD-2024-008',
    opdracht_naam: 'Jaarrekening 2024 VOF',
    klant_id: '6',
    klant_naam: 'Fysiotherapie Vitaal VOF',
    type_opdracht: 'Jaarrekening',
    categorie: 'Traditie',
    status: 'In behandeling',
    priority: 'Hoog',
    boekjaar_periode: '2024',
    start_datum: '2025-03-01',
    deadline: '2025-05-31',
    geschat_aantal_uren: 10,
    gefactureerd_bedrag: 2000,
    betaald: false,
    verantwoordelijk: 'Harm-Jan Kaspers',
    document_ids: [],
    beschrijving: 'Jaarrekening VOF + winstverdelingen',
    bijzonderheden: 'Winstverdeling 50/50. Investering nieuwe apparatuur Q3 2024.',
  },
];

// ============================================
// MOCK TAKEN
// ============================================
export const mockTaken: Taak[] = [
  {
    id: '1',
    taak_nummer: 'TAAK-2024-0001',
    taak_omschrijving: 'Aanvullende stukken opvragen IB aangifte 2023',
    notities: 'Bankafschriften Q3 en Q4 2023 nodig',
    toegewezen_aan: 'Harm-Jan Kaspers',
    created_by: 'Harm-Jan Kaspers',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    gerelateerde_interactie_id: '2',
    project_id: '1',
    status: 'Te doen',
    priority: 'Hoog',
    created_at: '2024-10-20T09:00:00Z',
    deadline: '2024-10-31',
    tags: ['IB Aangifte 2023', 'Documenten'],
    dagen_tot_deadline: 8,
    is_overdue: false,
    dagen_open: 3,
  },
  {
    id: '2',
    taak_nummer: 'TAAK-2024-0002',
    taak_omschrijving: 'Followup bellen na BTW aangifte',
    notities: 'Bespreken hoe het ging en of er nog vragen zijn',
    toegewezen_aan: 'Harm-Jan Kaspers',
    created_by: 'Harm-Jan Kaspers',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    gerelateerde_interactie_id: '2',
    project_id: '1',
    status: 'Te doen',
    priority: 'Laag',
    created_at: '2024-10-22T10:30:00Z',
    deadline: '2024-11-15',
    tags: ['BTW Aangifte Q2 2024', 'Opvolging'],
    dagen_tot_deadline: 23,
    is_overdue: false,
    dagen_open: 1,
  },
  {
    id: '3',
    taak_nummer: 'TAAK-2024-0003',
    taak_omschrijving: 'Beoordelen balans Q3',
    notities: 'Grondig checken op fouten voordat het naar de klant gaat',
    toegewezen_aan: 'Jan Jansen',
    created_by: 'Jan Jansen',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    project_id: '5',
    gerelateerde_interactie_id: '3',
    status: 'In uitvoering',
    priority: 'Hoog',
    created_at: '2024-10-18T14:00:00Z',
    deadline: '2024-10-30',
    tags: ['Jaarrekening 2024', 'Controle'],
    dagen_tot_deadline: 7,
    is_overdue: false,
    dagen_open: 5,
  },
];

// ============================================
// MOCK INTERACTIES
// ============================================
export const mockInteracties: Interactie[] = [
  {
    id: '1',
    interaction_nummer: 'INT-2024-0001',
    datum: '2024-10-23',
    tijd: '14:32',
    created_at: '2024-10-23T14:32:00Z',
    updated_at: '2024-10-23T14:36:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'WhatsApp',
    type: 'Inbound',
    onderwerp: 'Vraag over factuur #12345',
    samenvatting: 'Klant had een vraag over een beschadigde levering. Probleem direct opgelost door vervanging aan te bieden.',
    status: 'Afgerond',
    opvolging_nodig: false,
    priority: 'Hoog',
    tags: ['Facturatie', 'Service'],
    sentiment: 'Positief',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
    conversatie_id: '1',
  },
  {
    id: '2',
    interaction_nummer: 'INT-2024-0002',
    datum: '2024-10-20',
    tijd: '10:15',
    created_at: '2024-10-20T10:15:00Z',
    updated_at: '2024-10-20T10:15:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'E-mail',
    type: 'Outbound',
    onderwerp: 'Aanvraag documenten BTW Q3',
    samenvatting: 'Email verzonden met verzoek om facturen en bankafschriften voor BTW aangifte Q3 2024.',
    status: 'In behandeling',
    opvolging_nodig: true,
    opvolging_datum: '2024-10-27',
    priority: 'Normaal',
    tags: ['BTW', 'Documenten'],
    sentiment: 'Neutraal',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
  {
    id: '3',
    interaction_nummer: 'INT-2024-0003',
    datum: '2024-10-18',
    tijd: '14:00',
    created_at: '2024-10-18T14:00:00Z',
    updated_at: '2024-10-18T14:45:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'Telefoon',
    type: 'Inbound',
    duur: 45,
    onderwerp: 'Vragen over groeibegeleiding',
    samenvatting: 'Uitgebreid gesprek gehad over mogelijkheden voor groeibegeleiding. Klant overweegt om hulp in te schakelen voor procesoptimalisatie.',
    status: 'Afgerond',
    opvolging_nodig: true,
    opvolging_datum: '2024-11-01',
    priority: 'Hoog',
    tags: ['Groei', 'Advies'],
    sentiment: 'Positief',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
];

// ============================================
// MOCK CONTACTPERSONEN
// ============================================
export const mockContactPersonen: ContactPersoon[] = [
  {
    id: '1',
    naam: 'Peter van Dam',
    functie: 'CFO',
    klant_id: '2',
    bedrijfsnaam: 'Tech Solutions BV',
    primair: true,
    email: 'peter@techsolutions.nl',
    telefoonnummer: '+31201234567',
    mobiel: '+31612345678',
    linkedin: 'https://linkedin.com/in/petervandam',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
    aantal_interacties: 35,
    laatste_contact: '2024-10-23',
  },
];

// ============================================
// MOCK PROJECT TEMPLATES
// ============================================
export const mockProjectTemplates = [
  {
    id: '1',
    name: 'BTW Aangifte Kwartaal',
    category: 'BTW' as const,
    description: 'Standaard workflow voor kwartaal BTW aangifte',
    default_duration_days: 30,
    task_templates: JSON.stringify([
      {
        name: 'Documentatie aanvragen',
        order: 1,
        duration_days: 5,
        requires_client: true,
        checklist: ['Verkoopfacturen verzamelen', 'Aankoopfacturen verzamelen', 'Bankafschriften controleren', 'Kassabonnen uploaden'],
      },
      {
        name: 'Controle & Verwerking',
        order: 2,
        duration_days: 7,
        requires_client: false,
        checklist: ['Facturen verwerken in systeem', 'BTW berekenen', 'Controleren op fouten', 'Interne review'],
      },
      {
        name: 'Aangifte indienen',
        order: 3,
        duration_days: 3,
        requires_client: false,
        checklist: ['Definitieve berekening maken', 'Aangifte indienen bij Belastingdienst', 'Bevestiging bewaren', 'Klant informeren'],
      },
      {
        name: 'Betaling & Afsluiting',
        order: 4,
        duration_days: 5,
        requires_client: true,
        checklist: ['Klant informeren over te betalen bedrag', 'Betaling monitoren', 'Bevestiging ontvangen', 'Dossier archiveren'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 156,
  },
  {
    id: '2',
    name: 'Hypotheek Aanvraag',
    category: 'Hypotheek' as const,
    description: 'Complete workflow voor hypotheek aanvraag begeleiding',
    default_duration_days: 60,
    task_templates: JSON.stringify([
      {
        name: 'Intake & Oriëntatie',
        order: 1,
        duration_days: 7,
        requires_client: true,
        checklist: ['Intakegesprek plannen', 'Financiële situatie bespreken', 'Woonwensen inventariseren', 'Voorlopige berekening maken'],
      },
      {
        name: 'Documentatie Verzamelen',
        order: 2,
        duration_days: 14,
        requires_client: true,
        checklist: ['ID bewijs verzamelen', 'Loonstroken laatste 3 maanden', 'Jaaropgave werkgever', 'Bankafschriften', 'Werkgeversverklaring'],
      },
      {
        name: 'Hypotheekadvies',
        order: 3,
        duration_days: 7,
        requires_client: false,
        checklist: ['Financiële analyse uitvoeren', "Scenario's opstellen", 'Adviesgesprek plannen', 'Hypotheekadviesrapport opstellen'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 23,
  },
  {
    id: '3',
    name: 'Jaarrekening Opstellen',
    category: 'Jaarrekening' as const,
    description: 'Workflow voor het opstellen van jaarrekening',
    default_duration_days: 45,
    task_templates: JSON.stringify([
      {
        name: 'Administratie Controleren',
        order: 1,
        duration_days: 10,
        requires_client: true,
        checklist: ['Alle facturen aangeleverd?', 'Bankafschriften compleet?', 'Openstaande posten bekend?', 'Voorlopige cijfers opstellen'],
      },
      {
        name: 'Balans Opstellen',
        order: 2,
        duration_days: 10,
        requires_client: false,
        checklist: ['Activa opstellen', 'Passiva opstellen', 'Afstemmen bankrekeningen', 'Correcties doorvoeren'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 89,
  },
];

// ============================================
// MOCK PROJECTS
// ============================================
export const mockProjects = [
  {
    id: '1',
    name: 'BTW Aangifte Q3 2025 - De Bakker BV',
    template_id: '1',
    client_id: '1',
    client_name: 'Rosemary Braun',
    category: 'BTW' as const,
    status: 'wacht-op-klant' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 35,
    responsible_team_member: 'Harm-Jan Kaspers',
    responsible_initials: 'HK',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: '2025-10-10',
    reminder_count: 1,
    created_at: '2025-09-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'BTW Aangifte Q3 2025 - Jansen Consultancy',
    template_id: '1',
    client_id: '2',
    client_name: 'Ronald Richards',
    category: 'BTW' as const,
    status: 'in-uitvoering' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 60,
    responsible_team_member: 'Jan Jansen',
    responsible_initials: 'JJ',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-01T10:00:00Z',
  },
  {
    id: '3',
    name: 'Hypotheek Aanvraag - Familie Pietersen',
    template_id: '2',
    client_id: '3',
    client_name: 'Cameron Williams',
    category: 'Hypotheek' as const,
    status: 'in-uitvoering' as const,
    start_date: '2025-09-15',
    deadline: '2025-11-15',
    completion_percentage: 45,
    responsible_team_member: 'Linda Prins',
    responsible_initials: 'LP',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-15T10:00:00Z',
  },
  {
    id: '4',
    name: 'BTW Aangifte Q4 2025 - De Bakker BV',
    template_id: '1',
    client_id: '1',
    client_name: 'Rosemary Braun',
    category: 'BTW' as const,
    status: 'niet-gestart' as const,
    start_date: '2025-12-01',
    deadline: '2026-01-25',
    completion_percentage: 0,
    responsible_team_member: 'Harm-Jan Kaspers',
    responsible_initials: 'HK',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-11-20T10:00:00Z',
  },
  {
    id: '5',
    name: 'Jaarrekening 2024 - Jansen Consultancy',
    template_id: '3',
    client_id: '2',
    client_name: 'Ronald Richards',
    category: 'Jaarrekening' as const,
    status: 'geblokkeerd' as const,
    start_date: '2025-01-15',
    deadline: '2026-03-31',
    completion_percentage: 20,
    responsible_team_member: 'Jan Jansen',
    responsible_initials: 'JJ',
    is_overdue: false,
    blocked_reason: 'Wacht op aanvullende bankafschriften 2024',
    last_reminder_sent: '2025-10-01',
    reminder_count: 3,
    created_at: '2025-01-10T10:00:00Z',
  },
  {
    id: '6',
    name: 'BTW Aangifte Q3 2025 - Bloemen & Co',
    template_id: '1',
    client_id: '3',
    client_name: 'Cameron Williams',
    category: 'BTW' as const,
    status: 'afgerond' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 100,
    responsible_team_member: 'Linda Prins',
    responsible_initials: 'LP',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-01T10:00:00Z',
  },
];
