import { InboxItem } from '@/types';

export const mockInboxItems: InboxItem[] = [
  // WhatsApp met goede match
  {
    id: 'inb-001',
    inbox_id: 'INB-2025-001',
    timestamp: '2025-11-27T08:15:00Z',
    kanaal: 'WhatsApp',
    richting: 'Inbound',
    raw_afzender: '+31612345678',
    raw_naam: 'Pieter N.',
    raw_content: 'Goedemorgen, ik heb een vraag over mijn BTW aangifte van vorig kwartaal. Kunnen jullie me terugbellen?',
    status: 'Nieuw',
    match_type: 'Telefoon',
    match_score: 85,
    match_details: 'Telefoonnummer komt overeen met contactpersoon',
    suggested_klant_id: 'K-2021-045',
    suggested_klant_naam: 'Bouwbedrijf Noordhuis BV',
    created_at: '2025-11-27T08:15:00Z',
  },
  // Email met exacte match
  {
    id: 'inb-002',
    inbox_id: 'INB-2025-002',
    timestamp: '2025-11-27T07:42:00Z',
    kanaal: 'E-mail',
    richting: 'Inbound',
    raw_afzender: 'h.mulder@installatiebedrijfmulder.nl',
    raw_naam: 'Hans Mulder',
    raw_onderwerp: 'Factuur december',
    raw_content: 'Beste Harm-Jan,\n\nKunnen jullie de factuur voor december alvast opsturen? We willen dit nog voor het einde van het jaar verwerken.\n\nMet vriendelijke groet,\nHans Mulder',
    status: 'Nieuw',
    match_type: 'Email',
    match_score: 95,
    match_details: 'Email adres is exacte match met klant',
    suggested_klant_id: 'K-2018-012',
    suggested_klant_naam: 'Installatiebedrijf Mulder BV',
    created_at: '2025-11-27T07:42:00Z',
  },
  // Telefoon gemist, geen match
  {
    id: 'inb-003',
    inbox_id: 'INB-2025-003',
    timestamp: '2025-11-27T09:30:00Z',
    kanaal: 'Telefoon',
    richting: 'Inbound',
    raw_afzender: '+31503456789',
    raw_content: 'Gemiste oproep. Geen voicemail achtergelaten.',
    status: 'Nieuw',
    match_type: 'Geen match',
    match_score: 0,
    created_at: '2025-11-27T09:30:00Z',
  },
  // WhatsApp met naam match
  {
    id: 'inb-004',
    inbox_id: 'INB-2025-004',
    timestamp: '2025-11-27T06:55:00Z',
    kanaal: 'WhatsApp',
    richting: 'Inbound',
    raw_afzender: '+31687654321',
    raw_naam: 'Lisa de Vries',
    raw_content: 'Hoi, ik heb vorige week met Jan gesproken over mijn jaarrekening. Is er al nieuws?',
    status: 'Nieuw',
    match_type: 'Naam',
    match_score: 70,
    match_details: 'Naam komt overeen met bestaande klant',
    suggested_klant_id: 'K-2020-089',
    suggested_klant_naam: 'Lisa de Vries (privé)',
    created_at: '2025-11-27T06:55:00Z',
  },
  // Email spam
  {
    id: 'inb-005',
    inbox_id: 'INB-2025-005',
    timestamp: '2025-11-27T05:30:00Z',
    kanaal: 'E-mail',
    richting: 'Inbound',
    raw_afzender: 'marketing@cheaploans.biz',
    raw_naam: 'Business Loans',
    raw_onderwerp: 'URGENT: Business loan pre-approved!',
    raw_content: 'Congratulations! Your business has been pre-approved for a loan up to €500,000...',
    status: 'Nieuw',
    match_type: 'Geen match',
    match_score: 0,
    created_at: '2025-11-27T05:30:00Z',
  },
  // Al afgehandeld - gematcht
  {
    id: 'inb-006',
    inbox_id: 'INB-2025-006',
    timestamp: '2025-11-26T14:20:00Z',
    kanaal: 'E-mail',
    richting: 'Inbound',
    raw_afzender: 'p.bakker@gmail.com',
    raw_naam: 'Peter Bakker',
    raw_onderwerp: 'RE: Belastingaangifte 2024',
    raw_content: 'Bedankt voor de snelle reactie! Ik heb de documenten bijgevoegd.',
    status: 'Gematcht',
    match_type: 'Email',
    match_score: 90,
    match_details: 'Email adres komt overeen',
    suggested_klant_id: 'K-2019-067',
    suggested_klant_naam: 'P. Bakker & M. Bakker-Smit',
    matched_klant_id: 'K-2019-067',
    matched_klant_naam: 'P. Bakker & M. Bakker-Smit',
    created_interactie_id: 'INT-2025-234',
    reviewed_by: 'Linda Prins',
    reviewed_at: '2025-11-26T14:35:00Z',
    created_at: '2025-11-26T14:20:00Z',
  },
  // In behandeling
  {
    id: 'inb-007',
    inbox_id: 'INB-2025-007',
    timestamp: '2025-11-26T16:45:00Z',
    kanaal: 'WhatsApp',
    richting: 'Inbound',
    raw_afzender: '+31698765432',
    raw_naam: 'Henk V.',
    raw_content: 'Kan iemand me bellen? Dringend.',
    status: 'In behandeling',
    match_type: 'Geen match',
    match_score: 0,
    notities: 'Probeer terug te bellen om te identificeren',
    created_at: '2025-11-26T16:45:00Z',
  },
  // Nieuwe klant aangemaakt
  {
    id: 'inb-008',
    inbox_id: 'INB-2025-008',
    timestamp: '2025-11-25T10:00:00Z',
    kanaal: 'E-mail',
    richting: 'Inbound',
    raw_afzender: 'info@nieuwbedrijf.nl',
    raw_naam: 'Mark Jansen',
    raw_onderwerp: 'Offerte aanvraag administratie',
    raw_content: 'Geachte heer/mevrouw,\n\nWij zijn een nieuw bedrijf in Stadskanaal en zoeken een accountant voor onze administratie. Kunnen jullie een offerte sturen?\n\nMet vriendelijke groet,\nMark Jansen\nNieuw Bedrijf BV',
    status: 'Nieuwe klant aangemaakt',
    match_type: 'Geen match',
    match_score: 0,
    created_klant_id: 'K-2025-091',
    created_interactie_id: 'INT-2025-230',
    reviewed_by: 'Linda Prins',
    reviewed_at: '2025-11-25T10:30:00Z',
    created_at: '2025-11-25T10:00:00Z',
  },
  // Spam gemarkeerd
  {
    id: 'inb-009',
    inbox_id: 'INB-2025-009',
    timestamp: '2025-11-25T08:15:00Z',
    kanaal: 'E-mail',
    richting: 'Inbound',
    raw_afzender: 'noreply@crypto-invest.io',
    raw_onderwerp: 'Invest in Bitcoin NOW!',
    raw_content: 'Limited time offer! Invest €1000 and get €10000 back...',
    status: 'Spam',
    match_type: 'Geen match',
    match_score: 0,
    reviewed_by: 'Linda Prins',
    reviewed_at: '2025-11-25T08:20:00Z',
    created_at: '2025-11-25T08:15:00Z',
  },
  // Telefoon met mogelijke match
  {
    id: 'inb-010',
    inbox_id: 'INB-2025-010',
    timestamp: '2025-11-27T10:05:00Z',
    kanaal: 'Telefoon',
    richting: 'Inbound',
    raw_afzender: '+31599123456',
    raw_content: 'Voicemail: "Hallo, met mevrouw Koopman van het horecabedrijf. Ik had een vraag over de BTW. Belt u mij terug?"',
    status: 'Nieuw',
    match_type: 'Naam',
    match_score: 65,
    match_details: 'Naam "Koopman" komt mogelijk overeen met Sandra Koopman',
    suggested_klant_id: 'K-2022-034',
    suggested_klant_naam: 'Drents Horecabedrijf BV',
    created_at: '2025-11-27T10:05:00Z',
  },
];
