import { User } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'usr-001',
    user_id: 'USR-001',
    name: 'Harm-Jan Kaspers',
    voornaam: 'Harm-Jan',
    achternaam: 'Kaspers',
    email: 'harmjan@kaspersadvies.nl',
    role: 'Owner',
    department: 'Management',
    specialisatie: ['Advies', 'VPB', 'Groeibegeleiding'],
    is_active: true,
    phone: '+31 599 123 456',
    mobile: '+31 6 12345678',
    hourly_rate: 95,
    max_clients: undefined,
    current_client_count: 45,
    can_access_bsn: true,
    can_manage_users: true,
    can_delete_records: true,
    language: 'nl',
    theme: 'system',
    created_at: '2015-01-01T00:00:00Z',
    updated_at: '2025-11-01T10:00:00Z',
    last_login: '2025-11-27T08:15:00Z',
  },
  {
    id: 'usr-002',
    user_id: 'USR-002',
    name: 'Jan Jansen',
    voornaam: 'Jan',
    achternaam: 'Jansen',
    email: 'jan@kaspersadvies.nl',
    role: 'Employee',
    department: 'Administration',
    specialisatie: ['MKB', 'BTW', 'Jaarrekening'],
    is_active: true,
    phone: '+31 599 123 457',
    mobile: '+31 6 23456789',
    hourly_rate: 55,
    max_clients: 50,
    current_client_count: 42,
    can_access_bsn: false,
    can_manage_users: false,
    can_delete_records: false,
    language: 'nl',
    theme: 'light',
    created_at: '2018-03-15T00:00:00Z',
    updated_at: '2025-10-20T14:30:00Z',
    last_login: '2025-11-27T07:45:00Z',
  },
  {
    id: 'usr-003',
    user_id: 'USR-003',
    name: 'Linda Prins',
    voornaam: 'Linda',
    achternaam: 'Prins',
    email: 'linda@kaspersadvies.nl',
    role: 'Employee',
    department: 'Administration',
    specialisatie: ['Particulier', 'Toeslagen', 'IB'],
    is_active: true,
    phone: '+31 599 123 458',
    mobile: '+31 6 34567890',
    hourly_rate: 50,
    max_clients: 60,
    current_client_count: 40,
    can_access_bsn: false,
    can_manage_users: false,
    can_delete_records: false,
    language: 'nl',
    theme: 'dark',
    created_at: '2020-06-01T00:00:00Z',
    updated_at: '2025-11-15T09:00:00Z',
    last_login: '2025-11-27T08:00:00Z',
  },
];

export const specialisatieOptions = [
  'MKB',
  'ZZP',
  'Particulier',
  'BTW',
  'Jaarrekening',
  'IB',
  'VPB',
  'Toeslagen',
  'Advies',
  'Groeibegeleiding',
];
