import { Conversation, Message, Interactie, Klant, Opdracht, Taak, ContactPersoon } from '@/types';

// ============================================
// MOCK CONVERSATIONS
// ============================================
export const mockConversations: Conversation[] = [
  {
    id: '1',
    conversation_nummer: 'CONV-2024-0001',
    status: 'open',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    contactpersoon_id: '1',
    primary_channel: 'WhatsApp',
    all_channels: ['WhatsApp', 'E-mail'],
    onderwerp: 'Question about invoice #12345',
    tags: ['Facturatie', 'Urgent'],
    created_at: '2024-10-23T08:30:00Z',
    updated_at: '2024-10-23T14:35:00Z',
    last_message_at: '2024-10-23T14:35:00Z',
    toegewezen_aan: 'Harm-Jan Kaspers',
    team_members: ['Harm-Jan Kaspers'],
    opvolging_nodig: false,
    priority: 'high',
    is_unread: false,
    message_count: 4,
    sentiment: 'positive',
  },
  {
    id: '2',
    conversation_nummer: 'CONV-2024-0002',
    status: 'open',
    klant_id: '2',
    klant_naam: 'Ronald Richards',
    primary_channel: 'E-mail',
    all_channels: ['E-mail'],
    onderwerp: 'BTW-aangifte Q3 2024',
    tags: ['BTW', 'Q3'],
    created_at: '2024-10-23T09:15:00Z',
    updated_at: '2024-10-23T10:20:00Z',
    last_message_at: '2024-10-23T10:20:00Z',
    toegewezen_aan: 'Jan Jansen',
    team_members: ['Jan Jansen'],
    opvolging_nodig: true,
    opvolging_datum: '2024-10-25',
    priority: 'normal',
    is_unread: true,
    message_count: 2,
    sentiment: 'neutral',
  },
  {
    id: '3',
    conversation_nummer: 'CONV-2024-0003',
    status: 'pending',
    klant_id: '3',
    klant_naam: 'Cameron Williams',
    primary_channel: 'Telefoon',
    all_channels: ['Telefoon', 'E-mail'],
    onderwerp: 'Jaarrekening 2023 - Aanvullende documenten',
    tags: ['Jaarrekening', '2023'],
    created_at: '2024-10-22T14:00:00Z',
    updated_at: '2024-10-23T11:45:00Z',
    last_message_at: '2024-10-23T11:45:00Z',
    toegewezen_aan: 'Linda Prins',
    team_members: ['Linda Prins'],
    opvolging_nodig: true,
    opvolging_datum: '2024-10-24',
    priority: 'high',
    is_unread: true,
    message_count: 5,
    sentiment: 'neutral',
  },
  {
    id: '4',
    conversation_nummer: 'CONV-2024-0004',
    status: 'open',
    klant_id: '4',
    klant_naam: 'Esther Howard',
    primary_channel: 'WhatsApp',
    all_channels: ['WhatsApp'],
    onderwerp: 'Startersbegeleiding - Eerste kennismaking',
    tags: ['Starter', 'Groei'],
    created_at: '2024-10-23T10:30:00Z',
    updated_at: '2024-10-23T12:15:00Z',
    last_message_at: '2024-10-23T12:15:00Z',
    toegewezen_aan: 'Harm-Jan Kaspers',
    team_members: ['Harm-Jan Kaspers'],
    opvolging_nodig: false,
    priority: 'normal',
    is_unread: false,
    message_count: 3,
    sentiment: 'positive',
  },
];

// ============================================
// MOCK MESSAGES
// ============================================
export const mockMessages: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      conversation_id: '1',
      content: 'Hello, I received a damaged product in my order #12345',
      timestamp: '2024-10-23T14:32:00Z',
      channel: 'WhatsApp',
      direction: 'inbound',
      from: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
        channel_identifier: '+31612345678',
      },
      to: {
        id: 'team1',
        naam: 'Kaspers Advies',
        type: 'team_member',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_123',
        status: 'delivered',
      },
      is_thread_start: true,
      delivery_status: 'delivered',
      attachments: [],
      contains_question: true,
      action_required: true,
      marked_important: false,
    },
    {
      id: 'm2',
      conversation_id: '1',
      content: "I'm very sorry to hear that. Can you send me a photo of the damage?",
      timestamp: '2024-10-23T14:33:00Z',
      channel: 'WhatsApp',
      direction: 'outbound',
      from: {
        id: 'team1',
        naam: 'Harm-Jan Kaspers',
        type: 'team_member',
      },
      to: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_124',
        status: 'read',
      },
      is_thread_start: false,
      delivery_status: 'read',
      read_at: '2024-10-23T14:33:30Z',
      attachments: [],
      contains_question: true,
      action_required: false,
      marked_important: false,
    },
    {
      id: 'm3',
      conversation_id: '1',
      content: 'Sure, here it is',
      timestamp: '2024-10-23T14:35:00Z',
      channel: 'WhatsApp',
      direction: 'inbound',
      from: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      to: {
        id: 'team1',
        naam: 'Kaspers Advies',
        type: 'team_member',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_125',
        status: 'delivered',
        media_type: 'image',
      },
      is_thread_start: false,
      delivery_status: 'delivered',
      attachments: [
        {
          id: 'att1',
          filename: 'damaged_product.jpg',
          file_type: 'image/jpeg',
          file_size: 245680,
          url: '/placeholder.svg',
          uploaded_at: '2024-10-23T14:35:00Z',
          uploaded_by: 'Rosemary Braun',
        },
      ],
      contains_question: false,
      action_required: true,
      marked_important: false,
    },
    {
      id: 'm4',
      conversation_id: '1',
      content: "Thank you. We'll send you a replacement immediately.",
      timestamp: '2024-10-23T14:36:00Z',
      channel: 'WhatsApp',
      direction: 'outbound',
      from: {
        id: 'team1',
        naam: 'Harm-Jan Kaspers',
        type: 'team_member',
      },
      to: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_126',
        status: 'read',
      },
      is_thread_start: false,
      delivery_status: 'read',
      read_at: '2024-10-23T14:36:15Z',
      attachments: [],
      contains_question: false,
      action_required: false,
      marked_important: false,
    },
  ],
};

// ============================================
// MOCK KLANTEN
// ============================================
export const mockKlanten: Klant[] = [
  {
    id: '1',
    klant_nummer: 'KL-2024-0001',
    naam: 'Rosemary Braun',
    type_klant: 'ZZP',
    klant_type_details: 'Grafisch ontwerper',
    email: 'rosemary.braun@example.com',
    telefoonnummer: '+31612345678',
    mobiel: '+31612345678',
    linkedin_url: 'https://linkedin.com/in/rosemarybraun',
    website: 'https://rosemarydesign.nl',
    adres: 'Kerkstraat 12',
    postcode: '1234 AB',
    plaats: 'Amsterdam',
    land: 'Nederland',
    factuur_adres: 'Postbus 5678',
    factuur_postcode: '1000 AB',
    factuur_plaats: 'Amsterdam',
    factuur_land: 'Nederland',
    geboortedatum: '1990-05-12',
    bsn: '123456782',
    kvk_nummer: '12345678',
    btw_nummer: 'NL123456782B01',
    iban: 'NL91ABNA0417164300',
    bic: 'ABNANL2A',
    bank_naam: 'ABN AMRO',
    betalingstermijn: 30,
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2022-03-15',
    gerelateerde_klanten: [],
    jaren_actief_als_ondernemer: 3,
    groei_fase: 'Groei',
    omzet_categorie: '50k-250k',
    tags: ['Creatief', 'Digital'],
    segment: 'Premium',
    voorkeur_kanaal: 'WhatsApp',
    taal_voorkeur: 'nl',
    laatste_contact_datum: '2024-10-23',
    aantal_interacties: 45,
    aantal_openstaande_opvolgingen: 1,
    aantal_opdrachten: 8,
    aantal_actieve_opdrachten: 2,
    jaren_als_klant: 2,
    engagement_score: 85,
  },
  {
    id: '2',
    klant_nummer: 'KL-2024-0002',
    naam: 'Ronald Richards',
    type_klant: 'MKB',
    klant_type_details: 'Tech Solutions BV',
    email: 'ronald@techsolutions.nl',
    telefoonnummer: '+31201234567',
    adres: 'Businesspark 45',
    postcode: '2500 CD',
    plaats: 'Den Haag',
    land: 'Nederland',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Jan Jansen',
    sinds_wanneer_klant: '2020-01-10',
    gerelateerde_klanten: [],
    jaren_actief_als_ondernemer: 8,
    groei_fase: 'Stabiel',
    omzet_categorie: '> 1M',
    tags: ['Tech', 'B2B'],
    segment: 'VIP',
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
    laatste_contact_datum: '2024-10-23',
    aantal_interacties: 120,
    aantal_openstaande_opvolgingen: 2,
    aantal_opdrachten: 32,
    aantal_actieve_opdrachten: 5,
    jaren_als_klant: 4,
    engagement_score: 92,
  },
  {
    id: '3',
    klant_nummer: 'KL-2024-0003',
    naam: 'Cameron Williams',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier',
    email: 'cameron.w@email.com',
    telefoonnummer: '+31687654321',
    adres: 'Dorpsweg 78',
    postcode: '3456 EF',
    plaats: 'Utrecht',
    land: 'Nederland',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Linda Prins',
    sinds_wanneer_klant: '2023-06-20',
    gerelateerde_klanten: [],
    tags: ['Particulier'],
    segment: 'Standard',
    voorkeur_kanaal: 'Telefoon',
    taal_voorkeur: 'nl',
    laatste_contact_datum: '2024-10-23',
    aantal_interacties: 12,
    aantal_openstaande_opvolgingen: 1,
    aantal_opdrachten: 3,
    aantal_actieve_opdrachten: 1,
    jaren_als_klant: 1,
    engagement_score: 68,
  },
  {
    id: '4',
    klant_nummer: 'KL-2024-0004',
    naam: 'Esther Howard',
    type_klant: 'ZZP',
    klant_type_details: 'Marketing consultant',
    email: 'esther@marketingpro.nl',
    telefoonnummer: '+31623456789',
    adres: 'Marktplein 5',
    postcode: '5678 GH',
    plaats: 'Rotterdam',
    land: 'Nederland',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2024-01-15',
    gerelateerde_klanten: [],
    jaren_actief_als_ondernemer: 1,
    groei_fase: 'Starter',
    omzet_categorie: '< 50k',
    tags: ['Starter', 'Marketing'],
    segment: 'Standard',
    voorkeur_kanaal: 'WhatsApp',
    taal_voorkeur: 'nl',
    laatste_contact_datum: '2024-10-23',
    aantal_interacties: 8,
    aantal_openstaande_opvolgingen: 0,
    aantal_opdrachten: 2,
    aantal_actieve_opdrachten: 1,
    jaren_als_klant: 0,
    engagement_score: 72,
  },
];

// ============================================
// MOCK OPDRACHTEN
// ============================================
export const mockOpdrachten: Opdracht[] = [
  {
    id: '1',
    opdracht_nummer: 'OPD-2024-0001',
    opdracht_naam: 'IB Aangifte 2023',
    beschrijving: 'Inkomstenbelasting aangifte 2023 voor Rosemary Braun',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    type_opdracht: 'IB (Inkomstenbelasting)',
    categorie: 'Traditie',
    status: 'In behandeling',
    priority: 'Normaal',
    start_datum: '2024-10-01',
    deadline: '2024-11-15',
    verantwoordelijk: 'Harm-Jan Kaspers',
    geschat_aantal_uren: 4,
    bestede_uren: 2,
    gefactureerd_bedrag: 450,
    betaald: false,
    document_ids: [],
    aantal_gerelateerde_interacties: 5,
    aantal_taken: 3,
    aantal_openstaande_taken: 2,
  },
  {
    id: '2',
    opdracht_nummer: 'OPD-2024-0002',
    opdracht_naam: 'BTW Q3 2024 - Tech Solutions',
    klant_id: '2',
    klant_naam: 'Ronald Richards',
    bedrijfsnaam: 'Tech Solutions BV',
    type_opdracht: 'BTW-aangifte',
    categorie: 'Traditie',
    status: 'Wacht op klant',
    priority: 'Hoog',
    start_datum: '2024-10-15',
    deadline: '2024-10-31',
    verantwoordelijk: 'Jan Jansen',
    geschat_aantal_uren: 3,
    bestede_uren: 1.5,
    gefactureerd_bedrag: 350,
    betaald: false,
    document_ids: [],
    dagen_tot_deadline: 8,
    aantal_gerelateerde_interacties: 3,
    aantal_taken: 2,
    aantal_openstaande_taken: 1,
  },
];

// ============================================
// MOCK TAKEN
// ============================================
export const mockTaken: Taak[] = [
  {
    id: '1',
    taak_nummer: 'TAAK-2024-0001',
    taak_omschrijving: 'Aanvullende stukken opvragen IB aangifte 2023',
    notities: 'Bankafschriften Q3 en Q4 2023 nodig',
    toegewezen_aan: 'Harm-Jan Kaspers',
    created_by: 'Harm-Jan Kaspers',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    gerelateerde_interactie_id: '2',
    project_id: '1',
    status: 'Te doen',
    priority: 'Hoog',
    created_at: '2024-10-20T09:00:00Z',
    deadline: '2024-10-31',
    tags: ['IB Aangifte 2023', 'Documenten'],
    dagen_tot_deadline: 8,
    is_overdue: false,
    dagen_open: 3,
  },
  {
    id: '2',
    taak_nummer: 'TAAK-2024-0002',
    taak_omschrijving: 'Followup bellen na BTW aangifte',
    notities: 'Bespreken hoe het ging en of er nog vragen zijn',
    toegewezen_aan: 'Harm-Jan Kaspers',
    created_by: 'Harm-Jan Kaspers',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    gerelateerde_interactie_id: '2',
    project_id: '1',
    status: 'Te doen',
    priority: 'Laag',
    created_at: '2024-10-22T10:30:00Z',
    deadline: '2024-11-15',
    tags: ['BTW Aangifte Q2 2024', 'Opvolging'],
    dagen_tot_deadline: 23,
    is_overdue: false,
    dagen_open: 1,
  },
  {
    id: '3',
    taak_nummer: 'TAAK-2024-0003',
    taak_omschrijving: 'Beoordelen balans Q3',
    notities: 'Grondig checken op fouten voordat het naar de klant gaat',
    toegewezen_aan: 'Jan Jansen',
    created_by: 'Jan Jansen',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    project_id: '5',
    gerelateerde_interactie_id: '3',
    status: 'In uitvoering',
    priority: 'Hoog',
    created_at: '2024-10-18T14:00:00Z',
    deadline: '2024-10-30',
    tags: ['Jaarrekening 2024', 'Controle'],
    dagen_tot_deadline: 7,
    is_overdue: false,
    dagen_open: 5,
  },
];

// ============================================
// MOCK INTERACTIES
// ============================================
export const mockInteracties: Interactie[] = [
  {
    id: '1',
    interaction_nummer: 'INT-2024-0001',
    datum: '2024-10-23',
    tijd: '14:32',
    created_at: '2024-10-23T14:32:00Z',
    updated_at: '2024-10-23T14:36:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'WhatsApp',
    type: 'Inbound',
    onderwerp: 'Vraag over factuur #12345',
    samenvatting: 'Klant had een vraag over een beschadigde levering. Probleem direct opgelost door vervanging aan te bieden.',
    status: 'Afgerond',
    opvolging_nodig: false,
    priority: 'Hoog',
    tags: ['Facturatie', 'Service'],
    sentiment: 'Positief',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
    conversatie_id: '1',
  },
  {
    id: '2',
    interaction_nummer: 'INT-2024-0002',
    datum: '2024-10-20',
    tijd: '10:15',
    created_at: '2024-10-20T10:15:00Z',
    updated_at: '2024-10-20T10:15:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'E-mail',
    type: 'Outbound',
    onderwerp: 'Aanvraag documenten BTW Q3',
    samenvatting: 'Email verzonden met verzoek om facturen en bankafschriften voor BTW aangifte Q3 2024.',
    status: 'In behandeling',
    opvolging_nodig: true,
    opvolging_datum: '2024-10-27',
    priority: 'Normaal',
    tags: ['BTW', 'Documenten'],
    sentiment: 'Neutraal',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
  {
    id: '3',
    interaction_nummer: 'INT-2024-0003',
    datum: '2024-10-18',
    tijd: '14:00',
    created_at: '2024-10-18T14:00:00Z',
    updated_at: '2024-10-18T14:45:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'Telefoon',
    type: 'Inbound',
    duur: 45,
    onderwerp: 'Vragen over groeibegeleiding',
    samenvatting: 'Uitgebreid gesprek gehad over mogelijkheden voor groeibegeleiding. Klant overweegt om hulp in te schakelen voor procesoptimalisatie.',
    status: 'Afgerond',
    opvolging_nodig: true,
    opvolging_datum: '2024-11-01',
    priority: 'Hoog',
    tags: ['Groei', 'Advies'],
    sentiment: 'Positief',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
];

// ============================================
// MOCK CONTACTPERSONEN
// ============================================
export const mockContactPersonen: ContactPersoon[] = [
  {
    id: '1',
    naam: 'Peter van Dam',
    functie: 'CFO',
    klant_id: '2',
    bedrijfsnaam: 'Tech Solutions BV',
    primair: true,
    email: 'peter@techsolutions.nl',
    telefoonnummer: '+31201234567',
    mobiel: '+31612345678',
    linkedin: 'https://linkedin.com/in/petervandam',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
    aantal_interacties: 35,
    laatste_contact: '2024-10-23',
  },
];

// ============================================
// MOCK PROJECT TEMPLATES
// ============================================
export const mockProjectTemplates = [
  {
    id: '1',
    name: 'BTW Aangifte Kwartaal',
    category: 'BTW' as const,
    description: 'Standaard workflow voor kwartaal BTW aangifte',
    default_duration_days: 30,
    task_templates: JSON.stringify([
      {
        name: 'Documentatie aanvragen',
        order: 1,
        duration_days: 5,
        requires_client: true,
        checklist: ['Verkoopfacturen verzamelen', 'Aankoopfacturen verzamelen', 'Bankafschriften controleren', 'Kassabonnen uploaden'],
      },
      {
        name: 'Controle & Verwerking',
        order: 2,
        duration_days: 7,
        requires_client: false,
        checklist: ['Facturen verwerken in systeem', 'BTW berekenen', 'Controleren op fouten', 'Interne review'],
      },
      {
        name: 'Aangifte indienen',
        order: 3,
        duration_days: 3,
        requires_client: false,
        checklist: ['Definitieve berekening maken', 'Aangifte indienen bij Belastingdienst', 'Bevestiging bewaren', 'Klant informeren'],
      },
      {
        name: 'Betaling & Afsluiting',
        order: 4,
        duration_days: 5,
        requires_client: true,
        checklist: ['Klant informeren over te betalen bedrag', 'Betaling monitoren', 'Bevestiging ontvangen', 'Dossier archiveren'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 156,
  },
  {
    id: '2',
    name: 'Hypotheek Aanvraag',
    category: 'Hypotheek' as const,
    description: 'Complete workflow voor hypotheek aanvraag begeleiding',
    default_duration_days: 60,
    task_templates: JSON.stringify([
      {
        name: 'Intake & Oriëntatie',
        order: 1,
        duration_days: 7,
        requires_client: true,
        checklist: ['Intakegesprek plannen', 'Financiële situatie bespreken', 'Woonwensen inventariseren', 'Voorlopige berekening maken'],
      },
      {
        name: 'Documentatie Verzamelen',
        order: 2,
        duration_days: 14,
        requires_client: true,
        checklist: ['ID bewijs verzamelen', 'Loonstroken laatste 3 maanden', 'Jaaropgave werkgever', 'Bankafschriften', 'Werkgeversverklaring'],
      },
      {
        name: 'Hypotheekadvies',
        order: 3,
        duration_days: 7,
        requires_client: false,
        checklist: ['Financiële analyse uitvoeren', "Scenario's opstellen", 'Adviesgesprek plannen', 'Hypotheekadviesrapport opstellen'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 23,
  },
  {
    id: '3',
    name: 'Jaarrekening Opstellen',
    category: 'Jaarrekening' as const,
    description: 'Workflow voor het opstellen van jaarrekening',
    default_duration_days: 45,
    task_templates: JSON.stringify([
      {
        name: 'Administratie Controleren',
        order: 1,
        duration_days: 10,
        requires_client: true,
        checklist: ['Alle facturen aangeleverd?', 'Bankafschriften compleet?', 'Openstaande posten bekend?', 'Voorlopige cijfers opstellen'],
      },
      {
        name: 'Balans Opstellen',
        order: 2,
        duration_days: 10,
        requires_client: false,
        checklist: ['Activa opstellen', 'Passiva opstellen', 'Afstemmen bankrekeningen', 'Correcties doorvoeren'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 89,
  },
];

// ============================================
// MOCK PROJECTS
// ============================================
export const mockProjects = [
  {
    id: '1',
    name: 'BTW Aangifte Q3 2025 - De Bakker BV',
    template_id: '1',
    client_id: '1',
    client_name: 'Rosemary Braun',
    category: 'BTW' as const,
    status: 'wacht-op-klant' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 35,
    responsible_team_member: 'Harm-Jan Kaspers',
    responsible_initials: 'HK',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: '2025-10-10',
    reminder_count: 1,
    created_at: '2025-09-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'BTW Aangifte Q3 2025 - Jansen Consultancy',
    template_id: '1',
    client_id: '2',
    client_name: 'Ronald Richards',
    category: 'BTW' as const,
    status: 'in-uitvoering' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 60,
    responsible_team_member: 'Jan Jansen',
    responsible_initials: 'JJ',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-01T10:00:00Z',
  },
  {
    id: '3',
    name: 'Hypotheek Aanvraag - Familie Pietersen',
    template_id: '2',
    client_id: '3',
    client_name: 'Cameron Williams',
    category: 'Hypotheek' as const,
    status: 'in-uitvoering' as const,
    start_date: '2025-09-15',
    deadline: '2025-11-15',
    completion_percentage: 45,
    responsible_team_member: 'Linda Prins',
    responsible_initials: 'LP',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-15T10:00:00Z',
  },
  {
    id: '4',
    name: 'BTW Aangifte Q4 2025 - De Bakker BV',
    template_id: '1',
    client_id: '1',
    client_name: 'Rosemary Braun',
    category: 'BTW' as const,
    status: 'niet-gestart' as const,
    start_date: '2025-12-01',
    deadline: '2026-01-25',
    completion_percentage: 0,
    responsible_team_member: 'Harm-Jan Kaspers',
    responsible_initials: 'HK',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-11-20T10:00:00Z',
  },
  {
    id: '5',
    name: 'Jaarrekening 2024 - Jansen Consultancy',
    template_id: '3',
    client_id: '2',
    client_name: 'Ronald Richards',
    category: 'Jaarrekening' as const,
    status: 'geblokkeerd' as const,
    start_date: '2025-01-15',
    deadline: '2026-03-31',
    completion_percentage: 20,
    responsible_team_member: 'Jan Jansen',
    responsible_initials: 'JJ',
    is_overdue: false,
    blocked_reason: 'Wacht op aanvullende bankafschriften 2024',
    last_reminder_sent: '2025-10-01',
    reminder_count: 3,
    created_at: '2025-01-10T10:00:00Z',
  },
  {
    id: '6',
    name: 'BTW Aangifte Q3 2025 - Bloemen & Co',
    template_id: '1',
    client_id: '3',
    client_name: 'Cameron Williams',
    category: 'BTW' as const,
    status: 'afgerond' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 100,
    responsible_team_member: 'Linda Prins',
    responsible_initials: 'LP',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-01T10:00:00Z',
  },
];
