import { Conversation, Message, Interactie, Klant, Opdracht, Taak, ContactPersoon } from '@/types';

// ============================================
// MOCK CONVERSATIONS
// ============================================
export const mockConversations: Conversation[] = [
  {
    id: '1',
    conversation_nummer: 'CONV-2024-0001',
    status: 'open',
    klant_id: '1',
    klant_naam: 'Hans Mulder (particulier)',
    contactpersoon_id: '1',
    primary_channel: 'WhatsApp',
    all_channels: ['WhatsApp', 'E-mail'],
    onderwerp: 'Vraag over auto van de zaak',
    tags: ['Financieel', 'Auto van de zaak'],
    created_at: '2025-10-20T09:15:00Z',
    updated_at: '2025-10-20T09:27:00Z',
    last_message_at: '2025-10-20T09:27:00Z',
    toegewezen_aan: 'Harm-Jan Kaspers',
    team_members: ['Harm-Jan Kaspers'],
    opvolging_nodig: true,
    opvolging_datum: '2025-10-25',
    priority: 'normal',
    is_unread: false,
    message_count: 1,
    sentiment: 'positive',
  },
  {
    id: '2',
    conversation_nummer: 'CONV-2024-0002',
    status: 'open',
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    primary_channel: 'Zoom',
    all_channels: ['Zoom', 'WhatsApp'],
    onderwerp: 'Intake procesoptimalisatie',
    tags: ['Intake', 'Procesoptimalisatie', 'Groei'],
    created_at: '2025-10-18T14:30:00Z',
    updated_at: '2025-10-18T15:15:00Z',
    last_message_at: '2025-10-18T15:15:00Z',
    toegewezen_aan: 'Jan Jansen',
    team_members: ['Jan Jansen'],
    opvolging_nodig: true,
    opvolging_datum: '2025-10-22',
    priority: 'high',
    is_unread: false,
    message_count: 1,
    sentiment: 'positive',
  },
];

// ============================================
// MOCK MESSAGES
// ============================================
export const mockMessages: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      conversation_id: '1',
      content: 'Hello, I received a damaged product in my order #12345',
      timestamp: '2024-10-23T14:32:00Z',
      channel: 'WhatsApp',
      direction: 'inbound',
      from: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
        channel_identifier: '+31612345678',
      },
      to: {
        id: 'team1',
        naam: 'Kaspers Advies',
        type: 'team_member',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_123',
        status: 'delivered',
      },
      is_thread_start: true,
      delivery_status: 'delivered',
      attachments: [],
      contains_question: true,
      action_required: true,
      marked_important: false,
    },
    {
      id: 'm2',
      conversation_id: '1',
      content: "I'm very sorry to hear that. Can you send me a photo of the damage?",
      timestamp: '2024-10-23T14:33:00Z',
      channel: 'WhatsApp',
      direction: 'outbound',
      from: {
        id: 'team1',
        naam: 'Harm-Jan Kaspers',
        type: 'team_member',
      },
      to: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_124',
        status: 'read',
      },
      is_thread_start: false,
      delivery_status: 'read',
      read_at: '2024-10-23T14:33:30Z',
      attachments: [],
      contains_question: true,
      action_required: false,
      marked_important: false,
    },
    {
      id: 'm3',
      conversation_id: '1',
      content: 'Sure, here it is',
      timestamp: '2024-10-23T14:35:00Z',
      channel: 'WhatsApp',
      direction: 'inbound',
      from: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      to: {
        id: 'team1',
        naam: 'Kaspers Advies',
        type: 'team_member',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_125',
        status: 'delivered',
        media_type: 'image',
      },
      is_thread_start: false,
      delivery_status: 'delivered',
      attachments: [
        {
          id: 'att1',
          filename: 'damaged_product.jpg',
          file_type: 'image/jpeg',
          file_size: 245680,
          url: '/placeholder.svg',
          uploaded_at: '2024-10-23T14:35:00Z',
          uploaded_by: 'Rosemary Braun',
        },
      ],
      contains_question: false,
      action_required: true,
      marked_important: false,
    },
    {
      id: 'm4',
      conversation_id: '1',
      content: "Thank you. We'll send you a replacement immediately.",
      timestamp: '2024-10-23T14:36:00Z',
      channel: 'WhatsApp',
      direction: 'outbound',
      from: {
        id: 'team1',
        naam: 'Harm-Jan Kaspers',
        type: 'team_member',
      },
      to: {
        id: '1',
        naam: 'Rosemary Braun',
        type: 'client',
      },
      channel_metadata: {
        channel: 'WhatsApp',
        whatsapp_message_id: 'wa_126',
        status: 'read',
      },
      is_thread_start: false,
      delivery_status: 'read',
      read_at: '2024-10-23T14:36:15Z',
      attachments: [],
      contains_question: false,
      action_required: false,
      marked_important: false,
    },
  ],
};

// ============================================
// MOCK KLANTEN (10 realistic clients from CSV)
// ============================================
export const mockKlanten: Klant[] = [
  // Hans Mulder - Particulier (privé klant van bedrijfseigenaar)
  {
    id: '1',
    klant_nummer: 'K-2021-045',
    naam: 'Hans Mulder (particulier)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'h.mulder@gmail.com',
    telefoonnummer: '+31-599-612345',
    adres: 'Stationsstraat 12',
    postcode: '9501 AB',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '234567891',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-03-15',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['2'], // Link to Installatiebedrijf Mulder BV
    relatie_type: 'Eigenaar van',
    notities: 'DGA van Installatiebedrijf Mulder BV. Privé aangifte + optimalisatie salary/dividend.',
    tags: ['DGA', 'Particulier'],
    voorkeur_kanaal: 'Telefoon',
    taal_voorkeur: 'nl',
  },
  // Installatiebedrijf Mulder BV - Zakelijk (bedrijf van Hans Mulder)
  {
    id: '2',
    klant_nummer: 'K-2021-046',
    naam: 'Installatiebedrijf Mulder BV',
    type_klant: 'MKB',
    klant_type_details: 'Zakelijk - BV',
    email: 'info@mulder-installatie.nl',
    telefoonnummer: '+31-599-612388',
    adres: 'Industrieweg 8',
    postcode: '9501 DK',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    kvk_nummer: '45678123',
    btw_nummer: 'NL456781234B01',
    website: 'www.mulder-installatie.nl',
    branche: 'Installatiebedrijf',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-03-15',
    jaren_actief_als_ondernemer: 4,
    facturatie_frequentie: 'Maandelijks',
    groei_fase: 'Groei',
    gerelateerde_klanten: ['1'], // Link to Hans Mulder particulier
    relatie_type: 'Eigendom van',
    notities: 'CV-installaties, sanitair, duurzame energie. 3 medewerkers, groeiambitie naar 8 medewerkers.',
    tags: ['MKB', 'Installatie', 'Groei'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Lisa de Vries - Particulier (privé klant van onderneemster)
  {
    id: '3',
    klant_nummer: 'K-2020-088',
    naam: 'Lisa de Vries (privé)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'lisa.devries@hotmail.com',
    telefoonnummer: '+31-599-623456',
    adres: 'Hoofdstraat 45',
    postcode: '9501 CC',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '345678902',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Jan Jansen',
    sinds_wanneer_klant: '2020-09-01',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['4'], // Link to Webshop TechGadgets
    relatie_type: 'Eigenaar van',
    notities: 'Eigenaar webshop TechGadgets. Privé aangifte IB.',
    tags: ['Particulier', 'ZZP'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Webshop TechGadgets - Zakelijk (eenmanszaak van Lisa)
  {
    id: '4',
    klant_nummer: 'K-2020-089',
    naam: 'Webshop TechGadgets',
    type_klant: 'ZZP',
    klant_type_details: 'Zakelijk - Eenmanszaak',
    email: 'info@techgadgets.nl',
    telefoonnummer: '+31-599-623457',
    adres: 'Hoofdstraat 45',
    postcode: '9501 CC',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    kvk_nummer: '56789234',
    btw_nummer: 'NL567892345B01',
    website: 'www.techgadgets.nl',
    branche: 'E-commerce',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Jan Jansen',
    sinds_wanneer_klant: '2020-09-01',
    jaren_actief_als_ondernemer: 4,
    facturatie_frequentie: 'Kwartaal',
    groei_fase: 'Schaal-op',
    gerelateerde_klanten: ['3'], // Link to Lisa de Vries privé
    relatie_type: 'Eigendom van',
    notities: 'Online verkoop gadgets en elektronica. Groei 40% per jaar, overweegt personeel.',
    tags: ['ZZP', 'E-commerce', 'Groei'],
    voorkeur_kanaal: 'WhatsApp',
    taal_voorkeur: 'nl',
  },
  // P. Bakker & M. Bakker-Smit - Particulier (gehuwd koppel)
  {
    id: '5',
    klant_nummer: 'K-2022-101',
    naam: 'P. Bakker & M. Bakker-Smit',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - gehuwd',
    email: 'p.bakker@gmail.com',
    telefoonnummer: '+31-599-634567',
    adres: 'Europaweg 23',
    postcode: '9501 TG',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '456789013',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Linda Prins',
    sinds_wanneer_klant: '2022-01-10',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: [],
    notities: 'Gezamenlijke IB-aangifte. Toeslagen (2 kinderen). Peter werkt in loondienst bij Siemens.',
    tags: ['Particulier', 'Gezin', 'Toeslagen'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Fysiotherapie Vitaal VOF - Zakelijk (vennootschap)
  {
    id: '6',
    klant_nummer: 'K-2021-120',
    naam: 'Fysiotherapie Vitaal VOF',
    type_klant: 'MKB',
    klant_type_details: 'Zakelijk - VOF/Maatschap',
    email: 'info@fysiovitaal.nl',
    telefoonnummer: '+31-599-645678',
    adres: 'Wilhelminastraat 12',
    postcode: '9501 HD',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    kvk_nummer: '67890345',
    btw_nummer: 'NL678903456B01',
    website: 'www.fysiovitaal.nl',
    branche: 'Gezondheidszorg',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-06-01',
    jaren_actief_als_ondernemer: 3,
    facturatie_frequentie: 'Kwartaal',
    groei_fase: 'Professionalisering',
    gerelateerde_klanten: ['7', '8'], // Links to Anne Bakker and Tom Willems
    relatie_type: 'Vennoot',
    notities: 'Fysiotherapiepraktijk, 2 vennoten, 1 medewerker. Overweging omzetting naar BV.',
    tags: ['MKB', 'Gezondheidszorg', 'VOF'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Anne Bakker - Particulier (vennoot VOF)
  {
    id: '7',
    klant_nummer: 'K-2021-121',
    naam: 'Anne Bakker (privé)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'anne.bakker@fysiovitaal.nl',
    telefoonnummer: '+31-599-656789',
    adres: 'Molenstraat 8',
    postcode: '9501 JK',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '567890124',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-06-01',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['6'], // Link to Fysiotherapie Vitaal VOF
    relatie_type: 'Vennoot',
    notities: 'Vennoot Fysiotherapie Vitaal VOF (50%). Privé aangifte winst uit onderneming.',
    tags: ['Particulier', 'Vennoot'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Tom Willems - Particulier (vennoot VOF)
  {
    id: '8',
    klant_nummer: 'K-2021-122',
    naam: 'Tom Willems (privé)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'tom.willems@fysiovitaal.nl',
    telefoonnummer: '+31-599-667890',
    adres: 'Oosterstraat 34',
    postcode: '9501 LP',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '678901235',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Harm-Jan Kaspers',
    sinds_wanneer_klant: '2021-06-01',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['6'], // Link to Fysiotherapie Vitaal VOF
    relatie_type: 'Vennoot',
    notities: 'Vennoot Fysiotherapie Vitaal VOF (50%). Privé aangifte winst uit onderneming.',
    tags: ['Particulier', 'Vennoot'],
    voorkeur_kanaal: 'E-mail',
    taal_voorkeur: 'nl',
  },
  // Slagerij Van Dijk - Zakelijk (eenmanszaak)
  {
    id: '9',
    klant_nummer: 'K-2019-033',
    naam: 'Slagerij Van Dijk',
    type_klant: 'MKB',
    klant_type_details: 'Zakelijk - Eenmanszaak',
    email: 'info@slagerijvandijk.nl',
    telefoonnummer: '+31-599-678901',
    adres: 'Marktplein 5',
    postcode: '9501 AB',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    kvk_nummer: '78901456',
    btw_nummer: 'NL789014567B01',
    website: 'www.slagerijvandijk.nl',
    branche: 'Detailhandel voeding',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Linda Prins',
    sinds_wanneer_klant: '2019-02-01',
    jaren_actief_als_ondernemer: 5,
    facturatie_frequentie: 'Maandelijks',
    groei_fase: 'Digitalisering',
    gerelateerde_klanten: ['10'], // Link to Jan van Dijk privé
    relatie_type: 'Eigendom van',
    notities: 'Traditionele slagerij, bestaat sinds 1995. Nu digitalisering: webshop, online bestellingen.',
    tags: ['MKB', 'Retail', 'Digitalisering'],
    voorkeur_kanaal: 'WhatsApp',
    taal_voorkeur: 'nl',
  },
  // Jan van Dijk - Particulier (eigenaar slagerij)
  {
    id: '10',
    klant_nummer: 'K-2019-034',
    naam: 'Jan van Dijk (privé)',
    type_klant: 'Particulier',
    klant_type_details: 'Particulier - alleenstaand',
    email: 'jan@slagerijvandijk.nl',
    telefoonnummer: '+31-599-678901',
    adres: 'Marktplein 5',
    postcode: '9501 AB',
    plaats: 'Stadskanaal',
    land: 'Nederland',
    bsn: '789012346',
    status: 'Actief',
    status_historisch: false,
    accountmanager: 'Linda Prins',
    sinds_wanneer_klant: '2019-02-01',
    facturatie_frequentie: 'Jaarlijks',
    gerelateerde_klanten: ['9'], // Link to Slagerij Van Dijk
    relatie_type: 'Eigenaar van',
    notities: 'Eigenaar Slagerij Van Dijk. Zoon Pieter werkt mee in bedrijf (geen vennoot).',
    tags: ['Particulier', 'ZZP'],
    voorkeur_kanaal: 'Telefoon',
    taal_voorkeur: 'nl',
  },
];

// ============================================
// MOCK OPDRACHTEN (Realistic opdrachten from CSV)
// ============================================
export const mockOpdrachten: Opdracht[] = [
  {
    id: '1',
    opdracht_nummer: 'OPD-2024-001',
    opdracht_naam: 'IB-aangifte 2024',
    beschrijving: 'Inkomstenbelasting aangifte 2024',
    klant_id: '1',
    klant_naam: 'Hans Mulder (particulier)',
    type_opdracht: 'IB (Inkomstenbelasting)',
    categorie: 'Traditie',
    status: 'Afgerond',
    priority: 'Normaal',
    boekjaar_periode: '2024',
    start_datum: '2025-03-01',
    deadline: '2025-05-01',
    afgerond_datum: '2025-04-15',
    geschat_aantal_uren: 3,
    gefactureerd_bedrag: 450,
    betaald: true,
    betalings_datum: '2025-04-20',
    verantwoordelijk: 'Harm-Jan Kaspers',
    goedkeurder: 'Harm-Jan Kaspers',
    goedgekeurd_door: 'Harm-Jan Kaspers',
    goedgekeurd_op: '2025-04-15T14:30:00Z',
    document_ids: [],
    bijzonderheden: 'Hypotheekrenteaftrek eigen woning. DGA-optimalisatie meegenomen.',
  },
  {
    id: '2',
    opdracht_nummer: 'OPD-2024-002',
    opdracht_naam: 'Jaarrekening 2024',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    bedrijfsnaam: 'Installatiebedrijf Mulder BV',
    type_opdracht: 'Jaarrekening',
    categorie: 'Traditie',
    status: 'Gereed voor controle',
    priority: 'Hoog',
    boekjaar_periode: '2024',
    start_datum: '2025-02-01',
    deadline: '2025-05-31',
    geschat_aantal_uren: 12,
    gefactureerd_bedrag: 2400,
    betaald: false,
    verantwoordelijk: 'Jan Jansen',
    team_members: ['Jan Jansen', 'Linda Prins'],
    goedkeurder: 'Harm-Jan Kaspers',
    document_ids: [],
    bijzonderheden: 'Groei 35% t.o.v. 2023. Investering bedrijfswagen Q4.',
    aantal_taken: 8,
    aantal_openstaande_taken: 1,
    aantal_taken_wacht_goedkeuring: 1,
    voortgang_percentage: 87,
  },
  {
    id: '3',
    opdracht_nummer: 'OPD-2024-003',
    opdracht_naam: 'Groeibegeleiding Q2-Q4 2025',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    type_opdracht: 'Groeibegeleiding',
    categorie: 'Groei',
    status: 'In behandeling',
    priority: 'Hoog',
    boekjaar_periode: '2025',
    start_datum: '2025-04-01',
    deadline: '2025-12-31',
    geschat_aantal_uren: 20,
    gefactureerd_bedrag: 3500,
    betaald: false,
    verantwoordelijk: 'Harm-Jan Kaspers',
    goedkeurder: 'Harm-Jan Kaspers',
    document_ids: [],
    beschrijving: 'Begeleiding groei 3 naar 8 medewerkers',
    bijzonderheden: 'Procesoptimalisatie, werving strategie, financiële groeiplan.',
    aantal_taken: 5,
    aantal_openstaande_taken: 4,
    voortgang_percentage: 20,
  },
  {
    id: '4',
    opdracht_nummer: 'OPD-2024-004',
    opdracht_naam: 'BTW-aangifte Q1 2025',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    type_opdracht: 'BTW-aangifte',
    categorie: 'Traditie',
    status: 'Afgerond',
    priority: 'Normaal',
    boekjaar_periode: '2025 Q1',
    start_datum: '2025-04-15',
    deadline: '2025-04-30',
    afgerond_datum: '2025-04-28',
    ingediend_datum: '2025-04-28',
    geschat_aantal_uren: 2,
    gefactureerd_bedrag: 350,
    betaald: true,
    betalings_datum: '2025-05-05',
    verantwoordelijk: 'Jan Jansen',
    goedkeurder: 'Harm-Jan Kaspers',
    goedgekeurd_door: 'Harm-Jan Kaspers',
    goedgekeurd_op: '2025-04-28T10:00:00Z',
    document_ids: [],
    beschrijving: 'BTW-aangifte eerste kwartaal 2025',
  },
  {
    id: '5',
    opdracht_nummer: 'OPD-2024-005',
    opdracht_naam: 'Jaarrekening 2024',
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    type_opdracht: 'Jaarrekening',
    categorie: 'Traditie',
    status: 'Afgerond',
    priority: 'Normaal',
    boekjaar_periode: '2024',
    start_datum: '2025-02-15',
    deadline: '2025-05-31',
    afgerond_datum: '2025-04-30',
    geschat_aantal_uren: 8,
    gefactureerd_bedrag: 1600,
    betaald: true,
    betalings_datum: '2025-05-10',
    verantwoordelijk: 'Jan Jansen',
    goedkeurder: 'Harm-Jan Kaspers',
    goedgekeurd_door: 'Harm-Jan Kaspers',
    goedgekeurd_op: '2025-04-30T11:00:00Z',
    document_ids: [],
    beschrijving: 'Jaarrekening eenmanszaak 2024',
    bijzonderheden: 'Omzetgroei 40%. Voorraadwaardering complex i.v.m. Chinese leveranciers.',
  },
  {
    id: '6',
    opdracht_nummer: 'OPD-2024-006',
    opdracht_naam: 'Procesoptimalisatie webshop',
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    type_opdracht: 'Procesoptimalisatie',
    categorie: 'Groei',
    status: 'In behandeling',
    priority: 'Hoog',
    boekjaar_periode: '2025',
    start_datum: '2025-05-01',
    deadline: '2025-09-30',
    geschat_aantal_uren: 15,
    gefactureerd_bedrag: 2500,
    betaald: false,
    verantwoordelijk: 'Jan Jansen',
    goedkeurder: 'Harm-Jan Kaspers',
    document_ids: [],
    beschrijving: 'Optimalisatie orderverwerking en voorraadmanagement',
    bijzonderheden: 'Doel: 30% tijdsbesparing. Focus op automatisering.',
    aantal_taken: 3,
    aantal_openstaande_taken: 2,
    voortgang_percentage: 33,
  },
  {
    id: '7',
    opdracht_nummer: 'OPD-2024-007',
    opdracht_naam: 'IB-aangifte 2024',
    klant_id: '5',
    klant_naam: 'P. Bakker & M. Bakker-Smit',
    type_opdracht: 'IB (Inkomstenbelasting)',
    categorie: 'Traditie',
    status: 'Afgerond',
    priority: 'Normaal',
    boekjaar_periode: '2024',
    start_datum: '2025-03-05',
    deadline: '2025-05-01',
    afgerond_datum: '2025-04-10',
    geschat_aantal_uren: 2,
    gefactureerd_bedrag: 400,
    betaald: true,
    betalings_datum: '2025-04-15',
    verantwoordelijk: 'Linda Prins',
    goedkeurder: 'Harm-Jan Kaspers',
    goedgekeurd_door: 'Harm-Jan Kaspers',
    goedgekeurd_op: '2025-04-10T09:30:00Z',
    document_ids: [],
    beschrijving: 'Gezamenlijke IB-aangifte 2024',
    bijzonderheden: 'Peter in loondienst. Hypotheekrenteaftrek.',
  },
  {
    id: '8',
    opdracht_nummer: 'OPD-2024-008',
    opdracht_naam: 'Jaarrekening 2024 VOF',
    klant_id: '6',
    klant_naam: 'Fysiotherapie Vitaal VOF',
    type_opdracht: 'Jaarrekening',
    categorie: 'Traditie',
    status: 'In behandeling',
    priority: 'Hoog',
    boekjaar_periode: '2024',
    start_datum: '2025-03-01',
    deadline: '2025-05-31',
    geschat_aantal_uren: 10,
    gefactureerd_bedrag: 2000,
    betaald: false,
    verantwoordelijk: 'Harm-Jan Kaspers',
    document_ids: [],
    beschrijving: 'Jaarrekening VOF + winstverdelingen',
    bijzonderheden: 'Winstverdeling 50/50. Investering nieuwe apparatuur Q3 2024.',
  },
];

// ============================================
// MOCK TAKEN (Realistic tasks from CSV)
// ============================================
export const mockTaken: Taak[] = [
  {
    id: '1',
    taak_nummer: 'TAAK-2024-001',
    taak_omschrijving: 'Doorrekenen fiscale gevolgen auto van de zaak (Tesla vs benzine)',
    notities: 'Elektrische auto bijtelling 16% vs benzine 22%. Hans overweegt Tesla Model 3.',
    created_by: 'Harm-Jan Kaspers',
    toegewezen_aan: 'Harm-Jan Kaspers',
    needs_approval: false,
    klant_id: '1',
    klant_naam: 'Hans Mulder (particulier)',
    gerelateerde_opdracht_id: '3',
    opdracht_naam: 'Groeibegeleiding Q2-Q4 2025',
    gerelateerde_interactie: 'Vraag over auto van de zaak',
    status: 'Te doen',
    priority: 'Normaal',
    created_at: '2025-10-20T09:30:00Z',
    deadline: '2025-10-25',
    tags: ['Fiscaal', 'Auto'],
  },
  {
    id: '2',
    taak_nummer: 'TAAK-2024-002',
    taak_omschrijving: 'Offerte akkoord verwerken Lisa (procesoptimalisatie)',
    notities: 'Offerte getekend. Kick-off gepland 12 september.',
    created_by: 'Jan Jansen',
    toegewezen_aan: 'Jan Jansen',
    needs_approval: false,
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    gerelateerde_opdracht_id: '6',
    opdracht_naam: 'Procesoptimalisatie webshop',
    gerelateerde_interactie: 'Offerte procesoptimalisatie',
    status: 'Afgerond',
    priority: 'Hoog',
    created_at: '2025-10-07T13:30:00Z',
    deadline: '2025-10-22',
    completed_at: '2025-10-12T10:00:00Z',
    tags: ['Offerte', 'Procesoptimalisatie'],
  },
  {
    id: '3',
    taak_nummer: 'TAAK-2024-003',
    taak_omschrijving: 'Berekening nieuwe toeslagen Peter & Petra versturen',
    notities: 'Zorgtoeslag vervalt. Kindgebonden budget €850 per kind.',
    created_by: 'Linda Prins',
    toegewezen_aan: 'Linda Prins',
    needs_approval: true,
    approval_status: 'approved',
    approved_by: 'Harm-Jan Kaspers',
    approved_at: '2025-10-11T10:00:00Z',
    klant_id: '5',
    klant_naam: 'P. Bakker & M. Bakker-Smit',
    gerelateerde_interactie: 'Wijziging toeslagen door inkomensverandering',
    status: 'Afgerond',
    priority: 'Hoog',
    created_at: '2025-10-10T09:40:00Z',
    deadline: '2025-10-11',
    submitted_for_approval_at: '2025-10-11T09:00:00Z',
    completed_at: '2025-10-11T11:00:00Z',
    tags: ['Toeslagen', 'Berekening'],
  },
  {
    id: '4',
    taak_nummer: 'TAAK-2024-004',
    taak_omschrijving: 'Bevestigingsmail afspraak 25 oktober versturen',
    notities: 'Afspraak groeibegeleiding 25 oktober 10:00 uur.',
    created_by: 'Harm-Jan Kaspers',
    toegewezen_aan: 'Harm-Jan Kaspers',
    needs_approval: false,
    klant_id: '1',
    klant_naam: 'Hans Mulder (particulier)',
    gerelateerde_opdracht_id: '3',
    opdracht_naam: 'Groeibegeleiding Q2-Q4 2025',
    gerelateerde_interactie: 'Bevestiging afspraak groeibegeleiding',
    status: 'Te doen',
    priority: 'Normaal',
    created_at: '2025-10-08T16:00:00Z',
    deadline: '2025-10-23',
    tags: ['Afspraak'],
  },
  {
    id: '5',
    taak_nummer: 'TAAK-2024-005',
    taak_omschrijving: 'Factuur BTW Q1 opnieuw versturen naar Karin',
    notities: 'Factuur in spam beland. Opnieuw verstuurd.',
    created_by: 'Linda Prins',
    toegewezen_aan: 'Linda Prins',
    needs_approval: false,
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    gerelateerde_opdracht_id: '4',
    opdracht_naam: 'BTW-aangifte Q1 2025',
    gerelateerde_interactie: 'Factuur BTW-aangifte Q1',
    status: 'Afgerond',
    priority: 'Laag',
    created_at: '2025-10-17T11:00:00Z',
    deadline: '2025-10-18',
    completed_at: '2025-10-17T14:30:00Z',
    tags: ['Factuur', 'BTW'],
  },
  {
    id: '6',
    taak_nummer: 'TAAK-2024-006',
    taak_omschrijving: 'Bespreking kassasysteem in workflow analyse traject',
    notities: 'Lightspeed of Shopify. Besproken in intake 20 september.',
    created_by: 'Linda Prins',
    toegewezen_aan: 'Linda Prins',
    needs_approval: false,
    klant_id: '9',
    klant_naam: 'Slagerij Van Dijk',
    gerelateerde_interactie: 'Vraag over online kassasysteem',
    status: 'Afgerond',
    priority: 'Normaal',
    created_at: '2025-10-15T16:30:00Z',
    deadline: '2025-09-20',
    completed_at: '2025-09-20T10:00:00Z',
    tags: ['Workflow', 'Kassasysteem'],
  },
  {
    id: '7',
    taak_nummer: 'TAAK-2024-007',
    taak_omschrijving: 'Offerte groeiplan VOF naar BV opstellen',
    notities: 'Scope: fiscale analyse, lijfrenteclausule, juridische procedure, tijdlijn. 18 uur à €185.',
    created_by: 'Harm-Jan Kaspers',
    toegewezen_aan: 'Harm-Jan Kaspers',
    needs_approval: false,
    klant_id: '6',
    klant_naam: 'Fysiotherapie Vitaal VOF',
    gerelateerde_interactie: 'Bespreking VOF naar BV omzetting',
    status: 'Te doen',
    priority: 'Hoog',
    created_at: '2025-10-14T12:10:00Z',
    deadline: '2025-11-01',
    tags: ['Offerte', 'VOF naar BV'],
  },
  {
    id: '8',
    taak_nummer: 'TAAK-2024-008',
    taak_omschrijving: 'Vervolgmail met toelichting toeslagen wijziging',
    notities: 'Uitleg gevolgen promotie Peter voor toeslagen.',
    created_by: 'Linda Prins',
    toegewezen_aan: 'Linda Prins',
    needs_approval: true,
    approval_status: 'approved',
    approved_by: 'Harm-Jan Kaspers',
    approved_at: '2025-09-06T09:45:00Z',
    klant_id: '5',
    klant_naam: 'P. Bakker & M. Bakker-Smit',
    gerelateerde_interactie: 'Bevestiging ontvangst nieuwe inkomensgegevens',
    status: 'Afgerond',
    priority: 'Normaal',
    created_at: '2025-09-05T10:30:00Z',
    deadline: '2025-09-06',
    submitted_for_approval_at: '2025-09-06T09:00:00Z',
    completed_at: '2025-09-06T10:00:00Z',
    tags: ['Toeslagen', 'Communicatie'],
  },
  // Nieuwe taken voor Jaarrekening 2024 (Opdracht #2) - Met workflow
  {
    id: '9',
    taak_nummer: 'TAAK-2024-009',
    taak_omschrijving: 'Beoordelen balans Q3 2024',
    notities: 'Controleren activa, passiva en voorzieningen',
    created_by: 'Harm-Jan Kaspers',
    toegewezen_aan: 'Jan Jansen',
    started_by: 'Jan Jansen',
    needs_approval: true,
    approval_status: 'pending',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    gerelateerde_opdracht_id: '2',
    opdracht_naam: 'Jaarrekening 2024',
    status: 'Gereed voor controle',
    priority: 'Hoog',
    created_at: '2025-04-01T09:00:00Z',
    started_at: '2025-04-02T10:00:00Z',
    submitted_for_approval_at: '2025-04-15T14:00:00Z',
    deadline: '2025-04-20',
    tags: ['Jaarrekening', 'Balans'],
    wacht_op_goedkeuring: true,
  },
  {
    id: '10',
    taak_nummer: 'TAAK-2024-010',
    taak_omschrijving: 'Afschrijvingen bedrijfsmiddelen berekenen',
    notities: 'Investering bedrijfswagen Q4 verwerken',
    created_by: 'Harm-Jan Kaspers',
    toegewezen_aan: 'Linda Prins',
    started_by: 'Linda Prins',
    needs_approval: true,
    approval_status: 'approved',
    approved_by: 'Harm-Jan Kaspers',
    approved_at: '2025-04-10T11:00:00Z',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    gerelateerde_opdracht_id: '2',
    opdracht_naam: 'Jaarrekening 2024',
    status: 'Afgerond',
    priority: 'Normaal',
    created_at: '2025-04-01T09:00:00Z',
    started_at: '2025-04-05T09:30:00Z',
    submitted_for_approval_at: '2025-04-10T10:00:00Z',
    completed_at: '2025-04-10T11:30:00Z',
    deadline: '2025-04-15',
    tags: ['Jaarrekening', 'Afschrijvingen'],
  },
  {
    id: '11',
    taak_nummer: 'TAAK-2024-011',
    taak_omschrijving: 'Rapport jaarrekening opstellen voor Harm-Jan',
    notities: 'Definitief rapport inclusief toelichting en analyse',
    created_by: 'Jan Jansen',
    toegewezen_aan: 'Jan Jansen',
    needs_approval: true,
    approval_status: 'pending',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    gerelateerde_opdracht_id: '2',
    opdracht_naam: 'Jaarrekening 2024',
    project_id: '1',
    status: 'In uitvoering',
    priority: 'Urgent',
    created_at: '2025-04-10T14:00:00Z',
    started_at: '2025-04-12T09:00:00Z',
    deadline: '2025-04-22',
    tags: ['Jaarrekening', 'Rapport'],
    dagen_tot_deadline: 2,
    dagen_open: 8,
  },
  {
    id: '1',
    taak_nummer: 'TAAK-2024-0001',
    taak_omschrijving: 'Aanvullende stukken opvragen IB aangifte 2023',
    notities: 'Bankafschriften Q3 en Q4 2023 nodig',
    created_by: 'Harm-Jan Kaspers',
    toegewezen_aan: 'Harm-Jan Kaspers',
    needs_approval: false,
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    gerelateerde_interactie_id: '2',
    project_id: '1',
    status: 'Te doen',
    priority: 'Hoog',
    created_at: '2024-10-20T09:00:00Z',
    deadline: '2024-10-31',
    tags: ['IB Aangifte 2023', 'Documenten'],
    dagen_tot_deadline: 8,
    is_overdue: false,
    dagen_open: 3,
  },
  {
    id: '2',
    taak_nummer: 'TAAK-2024-0002',
    taak_omschrijving: 'Followup bellen na BTW aangifte',
    notities: 'Bespreken hoe het ging en of er nog vragen zijn',
    created_by: 'Harm-Jan Kaspers',
    toegewezen_aan: 'Harm-Jan Kaspers',
    needs_approval: false,
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    gerelateerde_interactie_id: '2',
    project_id: '1',
    status: 'Te doen',
    priority: 'Laag',
    created_at: '2024-10-22T10:30:00Z',
    deadline: '2024-11-15',
    tags: ['BTW Aangifte Q2 2024', 'Opvolging'],
    dagen_tot_deadline: 23,
    is_overdue: false,
    dagen_open: 1,
  },
  {
    id: '3',
    taak_nummer: 'TAAK-2024-0003',
    taak_omschrijving: 'Beoordelen balans Q3',
    notities: 'Grondig checken op fouten voordat het naar de klant gaat',
    created_by: 'Jan Jansen',
    toegewezen_aan: 'Jan Jansen',
    needs_approval: true,
    approval_status: 'pending',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    project_id: '5',
    gerelateerde_interactie_id: '3',
    status: 'In uitvoering',
    priority: 'Hoog',
    created_at: '2024-10-18T14:00:00Z',
    deadline: '2024-10-30',
    tags: ['Jaarrekening 2024', 'Controle'],
    dagen_tot_deadline: 7,
    is_overdue: false,
    dagen_open: 5,
  },
];

// ============================================
// MOCK INTERACTIES (Realistic interactions from CSV)
// ============================================
export const mockInteracties: Interactie[] = [
  {
    id: '1',
    interaction_nummer: 'INT-2025-001',
    datum: '2025-10-20',
    tijd: '09:15',
    created_at: '2025-10-20T09:15:00Z',
    updated_at: '2025-10-20T09:27:00Z',
    klant_id: '1',
    klant_naam: 'Hans Mulder (particulier)',
    klant_nummer: 'K-2021-045',
    gerelateerde_klanten: 'Installatiebedrijf Mulder BV',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'Telefoon',
    type: 'Inbound',
    duur: 12,
    onderwerp: 'Vraag over auto van de zaak',
    samenvatting: 'Hans belt over de fiscale behandeling van zijn bedrijfsauto. Besproken: bijtelling privégebruik, lease vs koop, elektrisch vs benzine. Advies: elektrische auto heeft lagere bijtelling (16% vs 22%). Hans overweegt Tesla Model 3. Afspraak: doorrekenen in groeibegeleiding traject.',
    opdracht_id: '2',
    opdracht_naam: 'Groeibegeleiding Q2-Q4 2025',
    status: 'Afgerond',
    opvolging_nodig: true,
    opvolging_datum: '2025-10-25',
    priority: 'Normaal',
    tags: ['Financieel', 'Auto van de zaak'],
    sentiment: 'Positief',
    externe_bestanden_id: 'INT-2025-001',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
  {
    id: '2',
    interaction_nummer: 'INT-2025-002',
    datum: '2025-10-18',
    tijd: '14:30',
    created_at: '2025-10-18T14:30:00Z',
    updated_at: '2025-10-18T15:15:00Z',
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    klant_nummer: 'K-2020-089',
    gerelateerde_klanten: 'Lisa de Vries (privé)',
    contactpersoon: 'Lisa de Vries',
    medewerker: 'Jan Jansen',
    kanaal: 'Zoom',
    type: 'Outbound',
    duur: 45,
    onderwerp: 'Intake procesoptimalisatie',
    samenvatting: 'Videogesprek met Lisa over procesoptimalisatie traject. Besproken: huidige knelpunten (handmatige orderverwerking, voorraadtekorten, retourprocessen). Lisa besteedt 15 uur/week aan admin die geautomatiseerd kan worden. Doel: 30% tijdsbesparing. Offerte opgesteld voor optimalisatietraject 15 uur à €165.',
    opdracht_id: '3',
    opdracht_naam: 'Procesoptimalisatie webshop',
    status: 'Afgerond',
    opvolging_nodig: true,
    opvolging_datum: '2025-10-22',
    priority: 'Hoog',
    tags: ['Intake', 'Procesoptimalisatie', 'Groei'],
    sentiment: 'Positief',
    externe_bestanden_id: 'INT-2025-002',
    is_read: true,
    read_by: ['Jan Jansen'],
  },
  {
    id: '3',
    interaction_nummer: 'INT-2025-003',
    datum: '2025-10-17',
    tijd: '10:45',
    created_at: '2025-10-17T10:45:00Z',
    updated_at: '2025-10-17T10:50:00Z',
    klant_id: '2',
    klant_naam: 'Installatiebedrijf Mulder BV',
    klant_nummer: 'K-2021-046',
    contactpersoon: 'Karin Jansen',
    medewerker: 'Linda Prins',
    kanaal: 'E-mail',
    type: 'Inbound',
    onderwerp: 'Factuur BTW-aangifte Q1',
    samenvatting: 'Karin vraagt wanneer de factuur voor BTW-aangifte Q1 verstuurd wordt. Antwoord: factuur is 5 mei verstuurd naar info@mulder-installatie.nl. Karin heeft deze niet ontvangen (spamfilter?). Factuur opnieuw doorgestuurd. Betaling binnen ontvangen op 5 juni.',
    opdracht_id: '4',
    opdracht_naam: 'BTW-aangifte Q1 2025',
    status: 'Afgerond',
    opvolging_nodig: false,
    priority: 'Normaal',
    tags: ['Financieel', 'Factuur'],
    sentiment: 'Neutraal',
    is_read: true,
    read_by: ['Linda Prins'],
  },
  {
    id: '4',
    interaction_nummer: 'INT-2025-004',
    datum: '2025-10-15',
    tijd: '16:20',
    created_at: '2025-10-15T16:20:00Z',
    updated_at: '2025-10-15T16:25:00Z',
    klant_id: '9',
    klant_naam: 'Slagerij Van Dijk',
    klant_nummer: 'K-2019-033',
    contactpersoon: 'Jan van Dijk',
    medewerker: 'Linda Prins',
    kanaal: 'WhatsApp',
    type: 'Inbound',
    onderwerp: 'Vraag over online kassasysteem',
    samenvatting: 'Jan stuurt bericht: \'Linda heb je ervaring met online kassasystemen voor webshop? Welke adviseer je?\' Antwoord: Lightspeed en Shopify hebben goede kassaintegraties. Bespreken in workflow analyse traject volgende week. Jan reageert met duim omhoog.',
    opdracht_id: '7',
    opdracht_naam: 'Workflow analyse + webshop setup',
    status: 'Afgerond',
    opvolging_nodig: false,
    priority: 'Normaal',
    tags: ['Digitalisering'],
    sentiment: 'Positief',
    externe_bestanden_id: 'INT-2025-003',
    is_read: true,
    read_by: ['Linda Prins'],
  },
  {
    id: '5',
    interaction_nummer: 'INT-2025-005',
    datum: '2025-10-14',
    tijd: '11:00',
    created_at: '2025-10-14T11:00:00Z',
    updated_at: '2025-10-14T12:02:00Z',
    klant_id: '6',
    klant_naam: 'Fysiotherapie Vitaal VOF',
    klant_nummer: 'K-2021-120',
    gerelateerde_klanten: 'Anne Bakker (privé), Tom Willems (privé)',
    contactpersoon: 'Anne Bakker, Tom Willems',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'Zoom',
    type: 'Outbound',
    duur: 62,
    onderwerp: 'Bespreking VOF naar BV omzetting',
    samenvatting: 'Videogesprek met beide vennoten over mogelijke omzetting VOF naar BV. Besproken: fiscale gevolgen (lijfrenteclausule, doorschuiffaciliteit), juridische procedure, kosten (notaris €1200, advies €3200). Voordelen BV: limited liability, pensioenopbouw, flexibeler bij overdracht. Anne en Tom willen offerte voor groeiplan inclusief BV-omzetting. Afspraak vervolgoverleg 1 september.',
    opdracht_id: '8',
    opdracht_naam: 'Groeiplan VOF naar BV',
    status: 'Afgerond',
    opvolging_nodig: true,
    opvolging_datum: '2025-11-01',
    priority: 'Hoog',
    tags: ['Groeiplan', 'Juridisch', 'VOF naar BV'],
    sentiment: 'Positief',
    externe_bestanden_id: 'INT-2025-004',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
  {
    id: '6',
    interaction_nummer: 'INT-2025-006',
    datum: '2025-10-10',
    tijd: '09:30',
    created_at: '2025-10-10T09:30:00Z',
    updated_at: '2025-10-10T09:38:00Z',
    klant_id: '5',
    klant_naam: 'P. Bakker & M. Bakker-Smit',
    klant_nummer: 'K-2022-101',
    contactpersoon: 'Petra Bakker-Smit',
    medewerker: 'Linda Prins',
    kanaal: 'Telefoon',
    type: 'Inbound',
    duur: 8,
    onderwerp: 'Wijziging toeslagen door inkomensverandering',
    samenvatting: 'Petra belt: Peter krijgt promotie bij Siemens, salaris stijgt van €48.000 naar €58.000 per jaar vanaf september. Vraag: invloed op toeslagen? Antwoord: zorgtoeslag vervalt waarschijnlijk, kindgebonden budget wordt minder. Advies: wijziging direct doorgeven Belastingdienst om terugvordering te voorkomen. Linda doet berekening en stuurt via mail.',
    opdracht_id: '6',
    opdracht_naam: 'Toeslagen 2025',
    status: 'Afgerond',
    opvolging_nodig: true,
    opvolging_datum: '2025-10-11',
    priority: 'Urgent',
    tags: ['Toeslagen', 'Urgent'],
    sentiment: 'Neutraal',
    externe_bestanden_id: 'INT-2025-005',
    is_read: true,
    read_by: ['Linda Prins'],
  },
  {
    id: '7',
    interaction_nummer: 'INT-2025-007',
    datum: '2025-10-08',
    tijd: '15:45',
    created_at: '2025-10-08T15:45:00Z',
    updated_at: '2025-10-08T15:50:00Z',
    klant_id: '1',
    klant_naam: 'Hans Mulder (particulier)',
    klant_nummer: 'K-2021-045',
    gerelateerde_klanten: 'Installatiebedrijf Mulder BV',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'E-mail',
    type: 'Outbound',
    onderwerp: 'Bevestiging afspraak groeibegeleiding',
    samenvatting: 'Mail verstuurd ter bevestiging afspraak 25 oktober 10:00 uur op kantoor. Agenda: personeelsplanning (van 3 naar 8 medewerkers), financieringsbehoefte, wervingsstrategie, salarisschalen. Hans wordt gevraagd huidige organogram en begroting mee te nemen.',
    opdracht_id: '2',
    opdracht_naam: 'Groeibegeleiding Q2-Q4 2025',
    status: 'Afgerond',
    opvolging_nodig: false,
    priority: 'Normaal',
    tags: ['Afspraak'],
    sentiment: 'Neutraal',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
  {
    id: '8',
    interaction_nummer: 'INT-2025-008',
    datum: '2025-10-07',
    tijd: '13:20',
    created_at: '2025-10-07T13:20:00Z',
    updated_at: '2025-10-07T13:25:00Z',
    klant_id: '4',
    klant_naam: 'Webshop TechGadgets',
    klant_nummer: 'K-2020-089',
    contactpersoon: 'Lisa de Vries',
    medewerker: 'Jan Jansen',
    kanaal: 'WhatsApp',
    type: 'Outbound',
    onderwerp: 'Offerte procesoptimalisatie',
    samenvatting: 'Offerte procesoptimalisatie via WhatsApp gestuurd (Lisa wilde het snel kunnen doornemen). 15 uur à €165 = €2.475 ex BTW. Scope: analyse huidige processen, automatiseringsadvies (Shopify apps), implementatiebegeleiding, nazorg 3 maanden. Lisa reageert: \'Ziet er goed uit, ik teken!\'. Bevestiging volgt per mail.',
    opdracht_id: '3',
    opdracht_naam: 'Procesoptimalisatie webshop',
    status: 'Afgerond',
    opvolging_nodig: true,
    opvolging_datum: '2025-10-09',
    priority: 'Hoog',
    tags: ['Offerte'],
    sentiment: 'Positief',
    externe_bestanden_id: 'INT-2025-006',
    is_read: true,
    read_by: ['Jan Jansen'],
  },
  {
    id: '1',
    interaction_nummer: 'INT-2024-0001',
    datum: '2024-10-23',
    tijd: '14:32',
    created_at: '2024-10-23T14:32:00Z',
    updated_at: '2024-10-23T14:36:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'WhatsApp',
    type: 'Inbound',
    onderwerp: 'Vraag over factuur #12345',
    samenvatting: 'Klant had een vraag over een beschadigde levering. Probleem direct opgelost door vervanging aan te bieden.',
    status: 'Afgerond',
    opvolging_nodig: false,
    priority: 'Hoog',
    tags: ['Facturatie', 'Service'],
    sentiment: 'Positief',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
    conversatie_id: '1',
  },
  {
    id: '2',
    interaction_nummer: 'INT-2024-0002',
    datum: '2024-10-20',
    tijd: '10:15',
    created_at: '2024-10-20T10:15:00Z',
    updated_at: '2024-10-20T10:15:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'E-mail',
    type: 'Outbound',
    onderwerp: 'Aanvraag documenten BTW Q3',
    samenvatting: 'Email verzonden met verzoek om facturen en bankafschriften voor BTW aangifte Q3 2024.',
    status: 'In behandeling',
    opvolging_nodig: true,
    opvolging_datum: '2024-10-27',
    priority: 'Normaal',
    tags: ['BTW', 'Documenten'],
    sentiment: 'Neutraal',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
  {
    id: '3',
    interaction_nummer: 'INT-2024-0003',
    datum: '2024-10-18',
    tijd: '14:00',
    created_at: '2024-10-18T14:00:00Z',
    updated_at: '2024-10-18T14:45:00Z',
    klant_id: '1',
    klant_naam: 'Rosemary Braun',
    medewerker: 'Harm-Jan Kaspers',
    kanaal: 'Telefoon',
    type: 'Inbound',
    duur: 45,
    onderwerp: 'Vragen over groeibegeleiding',
    samenvatting: 'Uitgebreid gesprek gehad over mogelijkheden voor groeibegeleiding. Klant overweegt om hulp in te schakelen voor procesoptimalisatie.',
    status: 'Afgerond',
    opvolging_nodig: true,
    opvolging_datum: '2024-11-01',
    priority: 'Hoog',
    tags: ['Groei', 'Advies'],
    sentiment: 'Positief',
    is_read: true,
    read_by: ['Harm-Jan Kaspers'],
  },
];

// ============================================
// MOCK CONTACTPERSONEN (Realistic contacts from CSV)
// ============================================
export const mockContactPersonen: ContactPersoon[] = [
  {
    id: '1',
    naam: 'Hans Mulder',
    functie: 'Directeur-eigenaar',
    klant_id: '2',
    bedrijfsnaam: 'Installatiebedrijf Mulder BV',
    primair: true,
    email: 'h.mulder@mulder-installatie.nl',
    telefoonnummer: '+31-599-612388',
    mobiel: '+31-6-12345678',
    linkedin: 'https://www.linkedin.com/in/hansmulder',
    is_ook_klant: 'Hans Mulder (particulier)',
    notities: 'Ook privé klant voor IB-aangifte',
    voorkeur_communicatie: 'Telefoon',
    taal_voorkeur: 'nl',
  },
  {
    id: '2',
    naam: 'Lisa de Vries',
    functie: 'Eigenaar',
    klant_id: '4',
    bedrijfsnaam: 'Webshop TechGadgets',
    primair: true,
    email: 'lisa@techgadgets.nl',
    telefoonnummer: '+31-599-623457',
    mobiel: '+31-6-23456789',
    linkedin: 'https://www.linkedin.com/in/lisadevries',
    is_ook_klant: 'Lisa de Vries (privé)',
    notities: 'Ook privé klant voor IB-aangifte',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
  },
  {
    id: '3',
    naam: 'Petra Bakker-Smit',
    functie: 'Partner',
    klant_id: '5',
    bedrijfsnaam: 'P. Bakker & M. Bakker-Smit',
    primair: true,
    email: 'm.bakker@gmail.com',
    telefoonnummer: '+31-599-634567',
    mobiel: '+31-6-34567890',
    notities: 'Echtgenote Peter Bakker',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
  },
  {
    id: '4',
    naam: 'Anne Bakker',
    functie: 'Fysiotherapeut / Vennoot',
    klant_id: '6',
    bedrijfsnaam: 'Fysiotherapie Vitaal VOF',
    primair: true,
    email: 'anne.bakker@fysiovitaal.nl',
    telefoonnummer: '+31-599-645678',
    mobiel: '+31-6-45678901',
    linkedin: 'https://www.linkedin.com/in/annebakker',
    is_ook_klant: 'Anne Bakker (privé)',
    notities: 'Ook privé klant (vennoot VOF)',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
  },
  {
    id: '5',
    naam: 'Tom Willems',
    functie: 'Fysiotherapeut / Vennoot',
    klant_id: '6',
    bedrijfsnaam: 'Fysiotherapie Vitaal VOF',
    primair: true,
    email: 'tom.willems@fysiovitaal.nl',
    telefoonnummer: '+31-599-645678',
    mobiel: '+31-6-56789012',
    linkedin: 'https://www.linkedin.com/in/tomwillems',
    is_ook_klant: 'Tom Willems (privé)',
    notities: 'Ook privé klant (vennoot VOF)',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
  },
  {
    id: '6',
    naam: 'Sandra de Vries',
    functie: 'Praktijkmanager',
    klant_id: '6',
    bedrijfsnaam: 'Fysiotherapie Vitaal VOF',
    primair: false,
    email: 'sandra@fysiovitaal.nl',
    telefoonnummer: '+31-599-645678',
    mobiel: '+31-6-67890123',
    notities: 'Praktijkmanager in dienst',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
  },
  {
    id: '7',
    naam: 'Jan van Dijk',
    functie: 'Eigenaar',
    klant_id: '9',
    bedrijfsnaam: 'Slagerij Van Dijk',
    primair: true,
    email: 'jan@slagerijvandijk.nl',
    telefoonnummer: '+31-599-678901',
    mobiel: '+31-6-78901234',
    is_ook_klant: 'Jan van Dijk (privé)',
    notities: 'Ook privé klant voor IB-aangifte',
    voorkeur_communicatie: 'Telefoon',
    taal_voorkeur: 'nl',
  },
  {
    id: '8',
    naam: 'Pieter van Dijk',
    functie: 'Medewerker',
    klant_id: '9',
    bedrijfsnaam: 'Slagerij Van Dijk',
    primair: false,
    email: 'pieter@slagerijvandijk.nl',
    telefoonnummer: '+31-599-678901',
    mobiel: '+31-6-89012345',
    notities: 'Zoon van Jan. Werkt mee maar geen vennoot',
    voorkeur_communicatie: 'WhatsApp',
    taal_voorkeur: 'nl',
  },
  {
    id: '9',
    naam: 'Karin Jansen',
    functie: 'Financieel administrateur',
    klant_id: '2',
    bedrijfsnaam: 'Installatiebedrijf Mulder BV',
    primair: false,
    email: 'k.jansen@mulder-installatie.nl',
    telefoonnummer: '+31-599-612388',
    mobiel: '+31-6-90123456',
    notities: 'Contactpersoon voor facturen en administratie',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
  },
  {
    id: '1',
    naam: 'Peter van Dam',
    functie: 'CFO',
    klant_id: '2',
    bedrijfsnaam: 'Tech Solutions BV',
    primair: true,
    email: 'peter@techsolutions.nl',
    telefoonnummer: '+31201234567',
    mobiel: '+31612345678',
    linkedin: 'https://linkedin.com/in/petervandam',
    voorkeur_communicatie: 'E-mail',
    taal_voorkeur: 'nl',
    aantal_interacties: 35,
    laatste_contact: '2024-10-23',
  },
];

// ============================================
// MOCK PROJECT TEMPLATES
// ============================================
export const mockProjectTemplates = [
  {
    id: '1',
    name: 'BTW Aangifte Kwartaal',
    category: 'BTW' as const,
    description: 'Standaard workflow voor kwartaal BTW aangifte',
    default_duration_days: 30,
    task_templates: JSON.stringify([
      {
        name: 'Documentatie aanvragen',
        order: 1,
        duration_days: 5,
        requires_client: true,
        checklist: ['Verkoopfacturen verzamelen', 'Aankoopfacturen verzamelen', 'Bankafschriften controleren', 'Kassabonnen uploaden'],
      },
      {
        name: 'Controle & Verwerking',
        order: 2,
        duration_days: 7,
        requires_client: false,
        checklist: ['Facturen verwerken in systeem', 'BTW berekenen', 'Controleren op fouten', 'Interne review'],
      },
      {
        name: 'Aangifte indienen',
        order: 3,
        duration_days: 3,
        requires_client: false,
        checklist: ['Definitieve berekening maken', 'Aangifte indienen bij Belastingdienst', 'Bevestiging bewaren', 'Klant informeren'],
      },
      {
        name: 'Betaling & Afsluiting',
        order: 4,
        duration_days: 5,
        requires_client: true,
        checklist: ['Klant informeren over te betalen bedrag', 'Betaling monitoren', 'Bevestiging ontvangen', 'Dossier archiveren'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 156,
  },
  {
    id: '2',
    name: 'Hypotheek Aanvraag',
    category: 'Hypotheek' as const,
    description: 'Complete workflow voor hypotheek aanvraag begeleiding',
    default_duration_days: 60,
    task_templates: JSON.stringify([
      {
        name: 'Intake & Oriëntatie',
        order: 1,
        duration_days: 7,
        requires_client: true,
        checklist: ['Intakegesprek plannen', 'Financiële situatie bespreken', 'Woonwensen inventariseren', 'Voorlopige berekening maken'],
      },
      {
        name: 'Documentatie Verzamelen',
        order: 2,
        duration_days: 14,
        requires_client: true,
        checklist: ['ID bewijs verzamelen', 'Loonstroken laatste 3 maanden', 'Jaaropgave werkgever', 'Bankafschriften', 'Werkgeversverklaring'],
      },
      {
        name: 'Hypotheekadvies',
        order: 3,
        duration_days: 7,
        requires_client: false,
        checklist: ['Financiële analyse uitvoeren', "Scenario's opstellen", 'Adviesgesprek plannen', 'Hypotheekadviesrapport opstellen'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 23,
  },
  {
    id: '3',
    name: 'Jaarrekening Opstellen',
    category: 'Jaarrekening' as const,
    description: 'Workflow voor het opstellen van jaarrekening',
    default_duration_days: 45,
    task_templates: JSON.stringify([
      {
        name: 'Administratie Controleren',
        order: 1,
        duration_days: 10,
        requires_client: true,
        checklist: ['Alle facturen aangeleverd?', 'Bankafschriften compleet?', 'Openstaande posten bekend?', 'Voorlopige cijfers opstellen'],
      },
      {
        name: 'Balans Opstellen',
        order: 2,
        duration_days: 10,
        requires_client: false,
        checklist: ['Activa opstellen', 'Passiva opstellen', 'Afstemmen bankrekeningen', 'Correcties doorvoeren'],
      },
    ]),
    created_at: '2024-01-01T10:00:00Z',
    created_by: 'Harm-Jan Kaspers',
    is_active: true,
    use_count: 89,
  },
];

// ============================================
// MOCK PROJECTS
// ============================================
export const mockProjects = [
  {
    id: '1',
    name: 'BTW Aangifte Q3 2025 - De Bakker BV',
    template_id: '1',
    client_id: '1',
    client_name: 'Rosemary Braun',
    category: 'BTW' as const,
    status: 'wacht-op-klant' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 35,
    responsible_team_member: 'Harm-Jan Kaspers',
    responsible_initials: 'HK',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: '2025-10-10',
    reminder_count: 1,
    created_at: '2025-09-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'BTW Aangifte Q3 2025 - Jansen Consultancy',
    template_id: '1',
    client_id: '2',
    client_name: 'Ronald Richards',
    category: 'BTW' as const,
    status: 'in-uitvoering' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 60,
    responsible_team_member: 'Jan Jansen',
    responsible_initials: 'JJ',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-01T10:00:00Z',
  },
  {
    id: '3',
    name: 'Hypotheek Aanvraag - Familie Pietersen',
    template_id: '2',
    client_id: '3',
    client_name: 'Cameron Williams',
    category: 'Hypotheek' as const,
    status: 'in-uitvoering' as const,
    start_date: '2025-09-15',
    deadline: '2025-11-15',
    completion_percentage: 45,
    responsible_team_member: 'Linda Prins',
    responsible_initials: 'LP',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-15T10:00:00Z',
  },
  {
    id: '4',
    name: 'BTW Aangifte Q4 2025 - De Bakker BV',
    template_id: '1',
    client_id: '1',
    client_name: 'Rosemary Braun',
    category: 'BTW' as const,
    status: 'niet-gestart' as const,
    start_date: '2025-12-01',
    deadline: '2026-01-25',
    completion_percentage: 0,
    responsible_team_member: 'Harm-Jan Kaspers',
    responsible_initials: 'HK',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-11-20T10:00:00Z',
  },
  {
    id: '5',
    name: 'Jaarrekening 2024 - Jansen Consultancy',
    template_id: '3',
    client_id: '2',
    client_name: 'Ronald Richards',
    category: 'Jaarrekening' as const,
    status: 'geblokkeerd' as const,
    start_date: '2025-01-15',
    deadline: '2026-03-31',
    completion_percentage: 20,
    responsible_team_member: 'Jan Jansen',
    responsible_initials: 'JJ',
    is_overdue: false,
    blocked_reason: 'Wacht op aanvullende bankafschriften 2024',
    last_reminder_sent: '2025-10-01',
    reminder_count: 3,
    created_at: '2025-01-10T10:00:00Z',
  },
  {
    id: '6',
    name: 'BTW Aangifte Q3 2025 - Bloemen & Co',
    template_id: '1',
    client_id: '3',
    client_name: 'Cameron Williams',
    category: 'BTW' as const,
    status: 'afgerond' as const,
    start_date: '2025-09-01',
    deadline: '2025-10-25',
    completion_percentage: 100,
    responsible_team_member: 'Linda Prins',
    responsible_initials: 'LP',
    is_overdue: false,
    blocked_reason: null,
    last_reminder_sent: null,
    reminder_count: 0,
    created_at: '2025-09-01T10:00:00Z',
  },
];
